/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tn.mariages.gui;

import com.alee.managers.notification.NotificationIcon;
import com.alee.managers.notification.NotificationManager;
import com.alee.managers.notification.NotificationOption;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.entities.Prestataire;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.UIManager;
import tn.mariages.dao.AdminDAO;
import tn.mariages.dao.ClientDAO;
import tn.mariages.util.FTPFileUploader;

/**
 *
 * @author cyrine
 */
public class AjoutPrestataire extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();

    Prestataire prest = new Prestataire();
    PrestataireDAO presDAO = new PrestataireDAO();
    String[] specialite = {"--Choisir Specialite--"};
    String[] categorie = {"--Choisir categorie--", "La mariée", "le mari", "Beauté", "La réception", "Gastronomie", "Annimation", "Voyages", "Photographe"};
    String[] ville = {"--Choisir ville--", "tunis", "arriana", "hammamet", "Sousse", "Carthage", "Mannouba"};
    String[] specialitMari = {"--Choisir Specialite--", "Costume", "Chaussure"};
    String[] specialitMariee = {"--Choisir Specialite--", "Robe marriée", "Haute couture", "Lingerie", "Bijoutier"};
    String[] specialitBeaute = {"--Choisir Specialite--", "Produit esthétique", "Maquillage Pro", "Sallon d'ethetique"};
    String[] specialitRecept = {"--Choisir Specialite--", "Forum", "Top happiness", "Le relais"};
    String[] specialitGastr = {"--Choisir Specialite--", "Traiteur", "Patisserie"};
    String[] specialitAnnim = {"--Choisir Specialite--", "Troupe musical", "Chanteurs", "Danseuse orientals"};
    String[] specialitVoyage = {"--Choisir Specialite--", "Agence de voyage"};
    String[] specialitPhotographe = {"--Choisir Specialite--", "Photographe paysagiste", "photographe classique"};

    public AjoutPrestataire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtNomPrest = new javax.swing.JTextField();
        jtAdrPrest = new javax.swing.JTextField();
        jtNumMobilPrest = new javax.swing.JTextField();
        jtEmailPrest = new javax.swing.JTextField();
        cmbVillePrest = new javax.swing.JComboBox();
        btnAjouterPrest = new javax.swing.JButton();
        btnAnnulerPrest = new javax.swing.JButton();
        jtpwdPrest = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescPrest = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jtNumFixePrest = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtImgPrest = new javax.swing.JTextField();
        btnParcourir = new javax.swing.JButton();
        cmbCategoriePrest = new javax.swing.JComboBox();
        cmbSpecialitePrest = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        chkCompteVerif = new javax.swing.JCheckBox();
        chkEmailVald = new javax.swing.JCheckBox();
        chkPremium = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jtDatePayement = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        erreurnomP = new javax.swing.JLabel();
        erreurmail = new javax.swing.JLabel();
        erreurmdp = new javax.swing.JLabel();
        erreuradr = new javax.swing.JLabel();
        erreurville = new javax.swing.JLabel();
        erreurcat = new javax.swing.JLabel();
        erreursp = new javax.swing.JLabel();
        erreurimg = new javax.swing.JLabel();
        erreurdesc = new javax.swing.JLabel();
        erreurnumM = new javax.swing.JLabel();
        erreurnumF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajout prestataire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nom:");

        jLabel3.setText("Description:");

        jLabel4.setText("Email:");

        jLabel5.setText("Mot de passe:");

        jLabel6.setText("Adresse:");

        jLabel7.setText("Num tel mobile:");

        jLabel8.setText("Catégorie:");

        jLabel9.setText("Spécialité:");

        jLabel10.setText("Ville:");

        jtNomPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomPrestFocusLost(evt);
            }
        });

        jtAdrPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAdrPrestFocusLost(evt);
            }
        });

        jtNumMobilPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumMobilPrestFocusLost(evt);
            }
        });

        jtEmailPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailPrestFocusLost(evt);
            }
        });

        cmbVillePrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbVillePrestFocusLost(evt);
            }
        });

        btnAjouterPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/circle_plus.png"))); // NOI18N
        btnAjouterPrest.setText("   Ajouter");
        btnAjouterPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterPrestActionPerformed(evt);
            }
        });

        btnAnnulerPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/close.png"))); // NOI18N
        btnAnnulerPrest.setText("   Annuler");
        btnAnnulerPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerPrestActionPerformed(evt);
            }
        });

        jtpwdPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtpwdPrestFocusLost(evt);
            }
        });

        jtDescPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDescPrestFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtDescPrest);

        jLabel11.setText("Num tel fixe:");

        jtNumFixePrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumFixePrestFocusLost(evt);
            }
        });

        jLabel12.setText("Image:");

        jtImgPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtImgPrestFocusLost(evt);
            }
        });

        btnParcourir.setText("Parcourir");
        btnParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcourirActionPerformed(evt);
            }
        });

        cmbCategoriePrest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoriePrestItemStateChanged(evt);
            }
        });
        cmbCategoriePrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriePrestActionPerformed(evt);
            }
        });
        cmbCategoriePrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbCategoriePrestFocusLost(evt);
            }
        });

        cmbSpecialitePrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbSpecialitePrestFocusLost(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abonnement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        chkCompteVerif.setText("Compte Verifier");

        chkEmailVald.setText("Email valide");

        chkPremium.setText("Premium");

        jLabel13.setText("Date payement:");

        jtDatePayement.setDateFormatString("yyyy MM dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCompteVerif)
                    .addComponent(jLabel13))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(chkEmailVald)
                        .addGap(68, 68, 68)
                        .addComponent(chkPremium))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDatePayement, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCompteVerif)
                    .addComponent(chkEmailVald)
                    .addComponent(chkPremium))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jtDatePayement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnAjouterPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(btnAnnulerPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(cmbVillePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(cmbCategoriePrest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(cmbSpecialitePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(erreurville, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(erreurcat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(erreursp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jtAdrPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(erreuradr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addComponent(jLabel11)
                                                                .addGap(22, 22, 22))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel7)
                                                                .addGap(8, 8, 8))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(210, 210, 210)
                                                                .addComponent(erreurnomP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jtpwdPrest, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(erreurmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(58, 58, 58)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel3)
                                                            .addComponent(jLabel12))
                                                        .addGap(28, 28, 28)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtImgPrest)
                                                    .addComponent(jtNumFixePrest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                                    .addComponent(jtNumMobilPrest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jtEmailPrest, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(erreurmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnParcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(62, 62, 62)
                                        .addComponent(jtNomPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(393, 393, 393)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(erreurdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erreurnumM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erreurnumF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erreurimg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(85, 85, 85))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCategoriePrest, cmbSpecialitePrest, cmbVillePrest, jtAdrPrest, jtEmailPrest, jtNomPrest, jtpwdPrest});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouterPrest, btnAnnulerPrest});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtNomPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtImgPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(erreurnomP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erreurimg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erreurdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtEmailPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(erreurmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtpwdPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(erreurmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jtAdrPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(erreuradr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(erreurnumM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnParcourir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(erreurville, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtNumMobilPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmbCategoriePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addComponent(erreurcat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(jtNumFixePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(erreursp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmbVillePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbSpecialitePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addComponent(erreurnumF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnulerPrest))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAjouterPrest, btnAnnulerPrest});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        for (int i = 0; i < categorie.length; i++) {
            cmbCategoriePrest.addItem(categorie[i]);

        }

        for (int i = 0; i < ville.length; i++) {
            cmbVillePrest.addItem(ville[i]);
        }
        for (int i = 0; i < specialite.length; i++) {
            cmbSpecialitePrest.addItem(specialite[i]);

        }

    }//GEN-LAST:event_formWindowOpened

    private void cmbCategoriePrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriePrestActionPerformed

        if (cmbCategoriePrest.getSelectedItem().toString().equals("La mariée")) {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitMariee.length; i++) {
                cmbSpecialitePrest.addItem(specialitMariee[i]);
            }
        }

        if (cmbCategoriePrest.getSelectedItem().toString().equals("le mari")) {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitMari.length; i++) {
                cmbSpecialitePrest.addItem(specialitMari[i]);
            }
        }

        if (cmbCategoriePrest.getSelectedItem().toString() == "Beauté") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitBeaute.length; i++) {
                cmbSpecialitePrest.addItem(specialitBeaute[i]);
            }
        }

        if (cmbCategoriePrest.getSelectedItem().toString() == "La réception") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitRecept.length; i++) {
                cmbSpecialitePrest.addItem(specialitRecept[i]);
            }
        }
        if (cmbCategoriePrest.getSelectedItem().toString() == "Gastronomie") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitGastr.length; i++) {
                cmbSpecialitePrest.addItem(specialitGastr[i]);
            }
        }

        if (cmbCategoriePrest.getSelectedItem().toString() == "Annimation") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitAnnim.length; i++) {
                cmbSpecialitePrest.addItem(specialitAnnim[i]);
            }
        }
        if (cmbCategoriePrest.getSelectedItem().toString() == "Voyages") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitVoyage.length; i++) {
                cmbSpecialitePrest.addItem(specialitVoyage[i]);
            }
        }

        if (cmbCategoriePrest.getSelectedItem().toString() == "Photographe") {
            cmbSpecialitePrest.removeAllItems();
            for (int i = 0; i < specialitPhotographe.length; i++) {
                cmbSpecialitePrest.addItem(specialitPhotographe[i]);
            }
        }


    }//GEN-LAST:event_cmbCategoriePrestActionPerformed

    private void cmbCategoriePrestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoriePrestItemStateChanged
    }//GEN-LAST:event_cmbCategoriePrestItemStateChanged

    private void btnAjouterPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterPrestActionPerformed

        Pattern pattern2 = Pattern.compile("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+");
        Pattern pattern = Pattern.compile("^\\d+$");
        Matcher matcher3 = pattern2.matcher(jtEmailPrest.getText());
        Matcher matcher = pattern.matcher(jtNumFixePrest.getText());
        Matcher matcher2 = pattern.matcher(jtNumMobilPrest.getText());

        Prestataire prestataire = new Prestataire();
        PrestataireDAO prestataireDAO = new PrestataireDAO();
        ClientDAO clientDAO = new ClientDAO();
        AdminDAO adminDAO = new AdminDAO();
        List<Prestataire> mylist = new ArrayList<Prestataire>();
        mylist = prestataireDAO.DisplayAllPrestataire();

        if (jtNomPrest.getText().equals("") || jtpwdPrest.getText().length() < 6 || jtDescPrest.getText().equals("") || jtEmailPrest.getText().equals("") || jtpwdPrest.getText().equals("") || jtAdrPrest.getText().equals("") || cmbVillePrest.getSelectedItem().equals("--Choisir ville--") || cmbSpecialitePrest.getSelectedItem().equals("--Choisir Specialite--") || cmbCategoriePrest.getSelectedItem().equals("--Choisir catégorie--") || !matcher.matches() || !matcher2.matches() || !matcher3.matches() || clientDAO.findClientByEmailBoolean(jtEmailPrest.getText()) || prestataireDAO.findPrestByEmailBoolean(jtEmailPrest.getText()) || adminDAO.findAdminByEmailBoolean(jtEmailPrest.getText())) {
            String ch = "";
            if (jtNomPrest.getText().equals("")) {
                erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }

            if (jtDescPrest.getText().equals("")) {
                erreurdesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (jtAdrPrest.getText().equals("")) {
               erreuradr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (cmbVillePrest.getSelectedItem().toString().equals("")) {
                erreurville.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (jtpwdPrest.getText().length() < 6) {
                erreurmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
                  NotificationManager.showNotification ( "le mot de passe doit contenir au moins 6 caracteres", NotificationIcon.warning.getIcon(), NotificationOption.apply, NotificationOption.discard );
               
            }
            if (jtNumMobilPrest.getText().equals("")) {
                erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            } else if (!matcher2.matches()) {
               erreurnumM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (jtNumFixePrest.getText().equals("")) {
                erreurnumF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            } else if (!matcher.matches()) {
                erreurnumF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }

            if (jtImgPrest.getText().equals("")) {
                erreurimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (jtEmailPrest.getText().equals("")) {
               erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            } else if (!matcher3.matches()) {
                erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (jtNumMobilPrest.getText().equals("")) {
                erreurnumM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (cmbCategoriePrest.getSelectedItem().toString().equals("--Choisir categorie--")) {
                erreurcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }

            if (clientDAO.findClientByEmailBoolean(jtEmailPrest.getText()) || prestataireDAO.findPrestByEmailBoolean(jtEmailPrest.getText()) || adminDAO.findAdminByEmailBoolean(jtEmailPrest.getText())) {
                 NotificationManager.showNotification ( "Cet email existe Deja", NotificationIcon.warning.getIcon() );

            }

            if (cmbSpecialitePrest.getSelectedItem().toString().equals("--Choisir Specialite--")) {
                erreursp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
          

        } else {

            prest.setNomPrest(jtNomPrest.getText());

            prest.setDescPrest(jtDescPrest.getText());

            prest.setAdrPrest(jtAdrPrest.getText());
            prest.setVillePrest(cmbVillePrest.getSelectedItem().toString());

            try {
                FTPFileUploader.getInstance().UploadPic(fc.getSelectedFile().getAbsolutePath(), "/prest/");
            } catch (IOException ex) {
                Logger.getLogger(AjoutClient.class.getName()).log(Level.SEVERE, null, ex);
            }
            String img = "http://mariages.tn/prest/" + fc.getSelectedFile().getName();
            prest.setImgPrest(img);

            prest.setEmailPrest(jtEmailPrest.getText());

            prest.setPwdPrest(jtpwdPrest.getText());
            prest.setCategorie(cmbCategoriePrest.getSelectedItem().toString());

            prest.setCompteValide(chkCompteVerif.isSelected());
            prest.setMailValide(chkEmailVald.isSelected());
            java.util.Date utilDate = jtDatePayement.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            prest.setDatePayement(sqlDate.toString());
            prest.setPremium(chkPremium.isSelected());

            prest.setSpecialite(cmbSpecialitePrest.getSelectedItem().toString());

            prest.setTelMobilePrest(jtNumMobilPrest.getText());
            prest.setTelFixePrest(jtNumMobilPrest.getText());
            presDAO.insertPrestataire(prest);

            this.dispose();
        }


    }//GEN-LAST:event_btnAjouterPrestActionPerformed

    private void btnAnnulerPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerPrestActionPerformed
        dispose();
    }//GEN-LAST:event_btnAnnulerPrestActionPerformed

    private void btnParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcourirActionPerformed
        String chemin = "";

        int retval = fc.showOpenDialog(null);

        if (retval == JFileChooser.APPROVE_OPTION) {

            chemin = fc.getSelectedFile().getAbsolutePath();
        }
                    chemin = chemin.replace("\\", "/");    }//GEN-LAST:event_btnParcourirActionPerformed

    private void jtNomPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomPrestFocusLost
        if (!jtNomPrest.getText().equals("")) {

            erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        } else {
            erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));        // TODO add your handling code here:
        }
    }//GEN-LAST:event_jtNomPrestFocusLost

    private void jtEmailPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailPrestFocusLost
        ClientDAO clientDao = new ClientDAO();
        AdminDAO adminDAO = new AdminDAO();
        PrestataireDAO prestataireDAO = new PrestataireDAO();
        Pattern pattern2 = Pattern.compile("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+");
        Matcher matcher3 = pattern2.matcher(jtEmailPrest.getText());
        if (jtEmailPrest.getText().equals("")) {
            erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else if ((clientDao.findClientByEmailBoolean(jtEmailPrest.getText()) || prestataireDAO.findPrestByEmailBoolean(jtEmailPrest.getText()) || adminDAO.findAdminByEmailBoolean(jtEmailPrest.getText()))) {
            erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else if (!matcher3.matches()) {
            erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else {
            erreurmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        }
    }//GEN-LAST:event_jtEmailPrestFocusLost

    private void jtpwdPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtpwdPrestFocusLost
        if (!jtpwdPrest.getText().equals("")) {
            erreurmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        } else {
            erreurmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jtpwdPrestFocusLost

    private void jtAdrPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAdrPrestFocusLost
        if (!jtAdrPrest.getText().equals("")) {
            erreuradr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        } else {
            erreuradr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));  }   // TODO add your handling code here:
    }//GEN-LAST:event_jtAdrPrestFocusLost

    private void cmbVillePrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbVillePrestFocusLost
        if (cmbVillePrest.getSelectedItem().toString().equals("--Choisir ville--")) {
            erreurville.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else {
            erreurville.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));  }      // TODO add your handling code here:
    }//GEN-LAST:event_cmbVillePrestFocusLost

    private void cmbCategoriePrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCategoriePrestFocusLost
        if (!cmbCategoriePrest.getSelectedItem().toString().equals("--Choisir catégorie--")) {
            erreurcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else {
            erreurcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg"))); }       // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriePrestFocusLost

    private void cmbSpecialitePrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbSpecialitePrestFocusLost
       if(!cmbSpecialitePrest.getSelectedItem().toString().equals("--Choisir specialité--"))
            erreursp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
       else
             erreursp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
    }//GEN-LAST:event_cmbSpecialitePrestFocusLost

    private void jtImgPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtImgPrestFocusLost
 if (!jtImgPrest.getText().equals("")) {
            erreurimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        } else {
            erreurimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));  }         // TODO add your handling code here:
    }//GEN-LAST:event_jtImgPrestFocusLost

    private void jtDescPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDescPrestFocusLost
 if(jtDescPrest.getText().equals(""))
             erreurdesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        else if(jtDescPrest.getText().length()<10)
                erreurdesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        else
                erreurdesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));        // TODO add your handling code here:
    }//GEN-LAST:event_jtDescPrestFocusLost

    private void jtNumMobilPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumMobilPrestFocusLost
         Pattern pattern = Pattern.compile("^[0-9]{8}+$");
   Matcher matcher = pattern.matcher(jtNumMobilPrest.getText());
    if(jtNumMobilPrest.getText().equals(""))
             {
               erreurnumM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else if(!matcher.matches())
             {
             erreurnumM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else{
                    erreurnumM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
             }
    
    }//GEN-LAST:event_jtNumMobilPrestFocusLost

    private void jtNumFixePrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumFixePrestFocusLost
         Pattern pattern = Pattern.compile("^[0-9]{8}+$");
   Matcher matcher = pattern.matcher(jtNumMobilPrest.getText());
    if(jtNumFixePrest.getText().equals(""))
             {
               erreurnumF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else if(!matcher.matches())
             {
             erreurnumF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else{
                    erreurnumF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
             } // TODO add your handling code here:
    }//GEN-LAST:event_jtNumFixePrestFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */

            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AjoutPrestataire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AjoutPrestataire.class.getName()).log(Level.SEVERE, null, ex);;
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AjoutPrestataire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AjoutPrestataire.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutPrestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } catch (Exception e) {
            //TODO exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutPrestataire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterPrest;
    private javax.swing.JButton btnAnnulerPrest;
    private javax.swing.JButton btnParcourir;
    private javax.swing.JCheckBox chkCompteVerif;
    private javax.swing.JCheckBox chkEmailVald;
    private javax.swing.JCheckBox chkPremium;
    private javax.swing.JComboBox cmbCategoriePrest;
    private javax.swing.JComboBox cmbSpecialitePrest;
    private javax.swing.JComboBox cmbVillePrest;
    private javax.swing.JLabel erreuradr;
    private javax.swing.JLabel erreurcat;
    private javax.swing.JLabel erreurdesc;
    private javax.swing.JLabel erreurimg;
    private javax.swing.JLabel erreurmail;
    private javax.swing.JLabel erreurmdp;
    private javax.swing.JLabel erreurnomP;
    private javax.swing.JLabel erreurnumF;
    private javax.swing.JLabel erreurnumM;
    private javax.swing.JLabel erreursp;
    private javax.swing.JLabel erreurville;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtAdrPrest;
    private com.toedter.calendar.JDateChooser jtDatePayement;
    private javax.swing.JTextPane jtDescPrest;
    private javax.swing.JTextField jtEmailPrest;
    private javax.swing.JTextField jtImgPrest;
    private javax.swing.JTextField jtNomPrest;
    private javax.swing.JTextField jtNumFixePrest;
    private javax.swing.JTextField jtNumMobilPrest;
    private javax.swing.JPasswordField jtpwdPrest;
    // End of variables declaration//GEN-END:variables
}
