/*
 * Copyright (C) 2014 khaled
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package tn.mariages.gui;


import tn.mariages.util.MySQLConnexion;
import com.alee.managers.notification.NotificationManager;
import com.alee.managers.notification.WebNotificationPopup;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import tn.mariages.dao.PaquetDAO;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.dao.ProduitDAO;
import tn.mariages.dao.ProduitPaquetDAO;
import tn.mariages.entities.Paquet;
import tn.mariages.entities.Prestataire;
import tn.mariages.entities.Produit;
import tn.mariages.entities.ProduitPaquet;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author khaled
 */
public class EspacePrest extends javax.swing.JFrame {

    /**
     * Creates new form EspacePrest
     */
    int id_prest;
    int id_prod;
    String[] Categories = {"Tous", "Salles de Fetes", "Centres de Coiffures", "Troupe Musical", "Photographe", "Agence de voyages de noces", "Restaurant", "Decorateur", "Fleuriste"};

    public EspacePrest() {
        initComponents();
        btnvalider.setVisible(false);
        cmbNomPaquet.setVisible(false);
    }

    
    public EspacePrest(int id,String cmt) {
        id_prest=id;
         
         try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
            UIManager.put("RootPane.setupButtonVisible", false);

    }
    catch(Exception e)
    {
        //TODO exception
    }
         
        initComponents();
        btnvalider.setVisible(false);
        cmbNomPaquet.setVisible(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AjouterPanier = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabCateg1 = new javax.swing.JLabel();
        LabSpec1 = new javax.swing.JLabel();
        LabDesc = new javax.swing.JLabel();
        labNom = new javax.swing.JLabel();
        labemail = new javax.swing.JLabel();
        LabAdr = new javax.swing.JLabel();
        LabCateg = new javax.swing.JLabel();
        LabTelMobile = new javax.swing.JLabel();
        LabTelFix = new javax.swing.JLabel();
        LabSpec = new javax.swing.JLabel();
        BtnModifierProfil = new javax.swing.JButton();
        LabImagePres = new javax.swing.JLabel();
        LabPremium = new javax.swing.JLabel();
        jlab = new javax.swing.JLabel();
        LabVille = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecomm = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textComm = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CmbCategori = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNomProduit = new javax.swing.JTextField();
        btnModifProduit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableProduit = new javax.swing.JTable();
        btnSuppProduit = new javax.swing.JButton();
        btnAjoutProd = new javax.swing.JButton();
        btnAjoutProdPaq = new javax.swing.JButton();
        cmbNomPaquet = new javax.swing.JComboBox();
        btnvalider = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePaquet = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        TFnOMpaquet = new javax.swing.JTextField();
        btnSuppPaquet = new javax.swing.JButton();
        btnModifPaquet = new javax.swing.JButton();
        btnAjoutPaquet = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setText("Nom :");

        jLabel2.setText("Description : ");

        jLabel4.setText("E-mail:");

        jLabel5.setText("Adresse : ");

        jLabel6.setText("Téléphone Fixe:");

        jLabel7.setText("Téléphone Mobile:");

        LabCateg1.setText("Categorie:");

        LabSpec1.setText("Specialité:");

        LabDesc.setText("jLabel10");

        labNom.setText("jLabel11");

        labemail.setText("jLabel13");

        LabAdr.setText("jLabel14");

        LabCateg.setText("jLabel15");

        LabTelMobile.setText("jLabel16");

        LabTelFix.setText("jLabel17");

        LabSpec.setText("jLabel18");

        BtnModifierProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Modify-icon.png"))); // NOI18N
        BtnModifierProfil.setText("Modifier");
        BtnModifierProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierProfilActionPerformed(evt);
            }
        });

        LabPremium.setText("jLabel3");
        LabPremium.setMaximumSize(new java.awt.Dimension(32, 32));
        LabPremium.setMinimumSize(new java.awt.Dimension(470, 414));
        LabPremium.setPreferredSize(new java.awt.Dimension(32, 32));

        jlab.setText("Ville: ");

        LabVille.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNom)
                            .addComponent(LabDesc)))
                    .addComponent(LabImagePres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnModifierProfil)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labemail)
                                    .addComponent(LabAdr)
                                    .addComponent(LabVille)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabCateg1)
                                    .addComponent(jLabel7)
                                    .addComponent(LabSpec1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabSpec)
                                    .addComponent(LabTelMobile)
                                    .addComponent(LabCateg)
                                    .addComponent(LabTelFix))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(LabImagePres, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labNom)
                            .addComponent(LabPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LabDesc)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labemail))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LabAdr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlab)
                            .addComponent(LabVille))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LabTelFix))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(LabTelMobile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabCateg1)
                            .addComponent(LabCateg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabSpec1)
                            .addComponent(LabSpec))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnModifierProfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tablecomm.setModel(new TableModelCommPrest());
        tablecomm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablecommMousePressed(evt);
            }
        });
        tablecomm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablecommKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablecommKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablecomm);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jScrollPane2.setViewportView(textComm);

        jLabel3.setText("Commentaire : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 474, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        CmbCategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbCategoriItemStateChanged(evt);
            }
        });
        CmbCategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCategoriActionPerformed(evt);
            }
        });

        jLabel11.setText("Catégorie:");

        jLabel13.setText("Nom Produit :");

        tfNomProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomProduitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomProduitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomProduitKeyTyped(evt);
            }
        });

        btnModifProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Modify-icon.png"))); // NOI18N
        btnModifProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifProduitActionPerformed(evt);
            }
        });

        tableProduit.setModel(new MyTableProduitPrest());
        tableProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableProduit);

        btnSuppProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/circle_delete.png"))); // NOI18N
        btnSuppProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppProduitActionPerformed(evt);
            }
        });

        btnAjoutProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/circle_plus.png"))); // NOI18N
        btnAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutProdActionPerformed(evt);
            }
        });

        btnAjoutProdPaq.setText("Ajouter dans un paquet");
        btnAjoutProdPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutProdPaqActionPerformed(evt);
            }
        });

        btnvalider.setText("Valider");
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CmbCategori, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(tfNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjoutProd)
                        .addGap(43, 43, 43)
                        .addComponent(btnModifProduit)
                        .addGap(52, 52, 52)
                        .addComponent(btnSuppProduit)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbNomPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnvalider))
                            .addComponent(btnAjoutProdPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbCategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(tfNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModifProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjoutProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuppProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAjoutProdPaq)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbNomPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnvalider))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paquet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tablePaquet.setModel( new TableListPaquetModel());
        tablePaquet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePaquetMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablePaquet);

        jLabel16.setText("Nom Paquet :");

        TFnOMpaquet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFnOMpaquetKeyReleased(evt);
            }
        });

        btnSuppPaquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppPaquetActionPerformed(evt);
            }
        });

        btnModifPaquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifPaquetActionPerformed(evt);
            }
        });

        btnAjoutPaquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutPaquetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel16)
                        .addGap(42, 42, 42)
                        .addComponent(TFnOMpaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnAjoutPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(108, 108, 108)
                            .addComponent(btnModifPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(btnSuppPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFnOMpaquet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuppPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjoutPaquet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Espace prestataire");

        btnPDF.setText("Générer PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjouterPanierLayout = new javax.swing.GroupLayout(AjouterPanier);
        AjouterPanier.setLayout(AjouterPanierLayout);
        AjouterPanierLayout.setHorizontalGroup(
            AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterPanierLayout.createSequentialGroup()
                .addGroup(AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(AjouterPanierLayout.createSequentialGroup()
                .addGap(498, 498, 498)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPDF)
                .addGap(51, 51, 51))
        );
        AjouterPanierLayout.setVerticalGroup(
            AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterPanierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AjouterPanierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AjouterPanier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AjouterPanier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModifierProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifierProfilActionPerformed

        this.setVisible(true);
        Modif_Prest PrestataireModif = new Modif_Prest();
        PrestataireModif.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        PrestataireModif.setVisible(true);
    }//GEN-LAST:event_BtnModifierProfilActionPerformed

    private void CmbCategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbCategoriItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCategoriItemStateChanged

    private void CmbCategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCategoriActionPerformed
        if (CmbCategori.getSelectedIndex() == 0) {
            tableProduit.setModel(new MyTableProduitPrest(id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 1) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[1], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 2) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[2], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 3) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[3], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 4) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[4], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 5) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[5], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 6) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[6], id_prest));
        }
        if (CmbCategori.getSelectedIndex() == 7) {
            tableProduit.setModel(new MyTableProduitByCatnPrest(Categories[7], id_prest));
        }
        tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
                    tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);
    }//GEN-LAST:event_CmbCategoriActionPerformed

    private void btnModifProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifProduitActionPerformed
        if (tableProduit.getSelectedRow() != -1) {
            Produit p = new Produit();

            p = new ProduitDAO().DisplayProdByID((int) tableProduit.getValueAt(tableProduit.getSelectedRow(), 0));
           /* ModifierProduit modifProd= new ModifierProduit(p.getIdProd(),id_prest);
            
            modifProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            modifProd.setVisible(true);*/
        } else {
            int dialogButton = JOptionPane.CANCEL_OPTION;
            JOptionPane.showConfirmDialog(null, "Vous n'avez selectionné aucun paquet", "Warning", dialogButton);
        }
    }//GEN-LAST:event_btnModifProduitActionPerformed

    private void tableProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitMouseClicked

        Produit p = new Produit();
        ProduitDAO pdao = new ProduitDAO();

        p = pdao.DisplayProdByID((int) tableProduit.getValueAt(tableProduit.getSelectedRow(), 0));
        if (evt.getClickCount() == 1) {
            TableModelCommPrest model = new TableModelCommPrest(p.getIdProd());
            tablecomm.setModel(model);
            tablecomm.getColumnModel().getColumn(0).setMinWidth(0);
                    tablecomm.getColumnModel().getColumn(0).setMaxWidth(0);

        } else if (evt.getClickCount() == 2) {

            this.setVisible(true);
            DetailsProduit detailproduit = new DetailsProduit(p);
            detailproduit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detailproduit.setVisible(true);

        }

    }//GEN-LAST:event_tableProduitMouseClicked

    private void tablePaquetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePaquetMouseClicked

        Paquet p = new Paquet();
        PaquetDAO pdao = new PaquetDAO();
        p = pdao.FindPaquetById((int) tablePaquet.getValueAt(tablePaquet.getSelectedRow(), 0));

        if (evt.getClickCount() == 2) {

            this.setVisible(true);

            DetailPaquet detailpaquet = new DetailPaquet(p);
            detailpaquet.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detailpaquet.setVisible(true);

        }

    }//GEN-LAST:event_tablePaquetMouseClicked

    private void btnSuppPaquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppPaquetActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Voulez vous supprimer tous les paquets selectionnés?", "Warning", dialogButton);

        if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here

            PaquetDAO pDAO = new PaquetDAO();
            int ids[] = new int[50];
            int j = -1;
            for (int i = 0; i < tablePaquet.getRowCount(); i++) {
                Boolean b = (Boolean) tablePaquet.getValueAt(i, 6);
                if (b) {
                    j++;
                    ids[j] = (int) tablePaquet.getValueAt(i, 0);
                }

            }
            while (j != -1) {
                pDAO.deletePaquet(ids[j]);
                j--;
            }
            TableListPaquetModel model = new TableListPaquetModel(id_prest);
            tablePaquet.setModel(model);
            tablePaquet.getColumnModel().getColumn(0).setMinWidth(0);
                    tablePaquet.getColumnModel().getColumn(0).setMaxWidth(0);
        }

    }//GEN-LAST:event_btnSuppPaquetActionPerformed

    @SuppressWarnings("unchecked")
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        MyTableProduitPrest modelprod = new MyTableProduitPrest(id_prest);
        tableProduit.setModel(modelprod);
        TableListPaquetModel modelpaq = new TableListPaquetModel(id_prest);
        tablePaquet.setModel(modelpaq);
        tablePaquet.getColumnModel().getColumn(0).setMinWidth(0);
        tablePaquet.getColumnModel().getColumn(0).setMaxWidth(0);
        tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
        tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);

        Prestataire p = new Prestataire();
        PrestataireDAO pdao = new PrestataireDAO();
        p = pdao.findPrestById(id_prest);
        labNom.setText(p.getNomPrest());
        LabAdr.setText(p.getAdrPrest());
        LabTelFix.setText(p.getTelFixePrest().toString());
        LabTelMobile.setText(p.getTelMobilePrest().toString());
        LabVille.setText(p.getVillePrest());
        LabSpec.setText(p.getSpecialite());
        LabCateg.setText(p.getCategorie());
        LabDesc.setText(p.getDescPrest());
        labemail.setText(p.getEmailPrest());
        //lab.setText(p.getNomPrest());
        ImageIcon icon;
            try {
                icon = new ImageIcon(new URL(p.getImgPrest().toString()));
                 icon = new ImageIcon(icon.getImage().getScaledInstance(180, 180, BufferedImage.SCALE_SMOOTH));
 LabImagePres.setIcon(icon);     

            } catch (MalformedURLException ex) {
                Logger.getLogger(ListeFeatProd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(p.isPremium()==true)
            {
                System.out.println("TRUE");
                icon = new ImageIcon("\\resources\\icons\\premium.png"); // to be changed
            icon = new ImageIcon(icon.getImage().getScaledInstance(32, 32, BufferedImage.SCALE_SMOOTH));
            LabPremium.setIcon(icon);
            }

        for (int i = 0; i < 7; i++) {
            CmbCategori.addItem(Categories[i]);
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnSuppProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppProduitActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Voulez vous supprimer tous les produits selectionnés?", "Warning", dialogButton);

        if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here
            for (int i = 0; i < tableProduit.getRowCount(); i++) {
                Boolean b = (Boolean) tableProduit.getValueAt(i, 6);
                if (b) {
                    new ProduitDAO().DeleteProd((int) tableProduit.getValueAt(i, 0));
                    
                    
                    WebNotificationPopup pop = new WebNotificationPopup();
                    pop.setContent("Le Produit a ete supprimer avec succes");
                    pop.setDisplayTime(5000);

                    NotificationManager.showNotification(pop);

                }
            }
            MyTableProduit model = new MyTableProduit();
            tableProduit.setModel(model);
            tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
            tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);
            CmbCategori.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnSuppProduitActionPerformed

    private void btnAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutProdActionPerformed
        // TODO add your handling code here:
        AjoutProduit ajout= new AjoutProduit(id_prest);
                ajout.setVisible(true);
        ajout.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_btnAjoutProdActionPerformed

    private void btnModifPaquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifPaquetActionPerformed
        // TODO add your handling code here:
        if (tablePaquet.getSelectedRow() != -1) {
            Paquet p = new Paquet();
            PaquetDAO pDAO = new PaquetDAO();
            p = pDAO.FindPaquetById((int) tablePaquet.getValueAt(tablePaquet.getSelectedRow(), 0));
            AjoutPaquet Modif = new AjoutPaquet(p);
            Modif.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            Modif.setVisible(true);
        } else {
            int dialogButton = JOptionPane.CANCEL_OPTION;
            JOptionPane.showConfirmDialog(null, "Vous n'avez selectionné aucun paquet", "Warning", dialogButton);
        }
    }//GEN-LAST:event_btnModifPaquetActionPerformed

    private void btnAjoutPaquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutPaquetActionPerformed
        // TODO add your handling code here:
        AjoutPaquet Ajout = new AjoutPaquet(id_prest);
        Ajout.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Ajout.setVisible(true);
    }//GEN-LAST:event_btnAjoutPaquetActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        MyTableProduitPrest modelprod = new MyTableProduitPrest(id_prest);
        tableProduit.setModel(modelprod);
        tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
            tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);
        TableListPaquetModel modelpaq = new TableListPaquetModel(id_prest);
        tablePaquet.setModel(modelpaq);
        tablePaquet.getColumnModel().getColumn(0).setMinWidth(0);
        tablePaquet.getColumnModel().getColumn(0).setMaxWidth(0);
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnAjoutProdPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutProdPaqActionPerformed
        // TODO add your handling code here:
        if (tableProduit.getSelectedRow() == -1) {
            int dialogButton = JOptionPane.OK_CANCEL_OPTION;
            JOptionPane.showConfirmDialog(null, "Vous n'avez selectionné aucun produit", "Warning", dialogButton);
        } else { //The ISSUE is here

            PaquetDAO pDAO = new PaquetDAO();
            List<Paquet> liste = new ArrayList<Paquet>();
            liste = pDAO.FindPaquetByPrest(id_prest);

            for (int i = 0; i < pDAO.DisplayAllPaquets().size(); i++) {
                cmbNomPaquet.addItem(liste.get(i).getNomPaquet());
            }
            cmbNomPaquet.setVisible(true);
            btnvalider.setVisible(true);

        }

    }//GEN-LAST:event_btnAjoutProdPaqActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:
        PaquetDAO pDAO = new PaquetDAO();
        ProduitPaquet prodpaq = new ProduitPaquet();
        ProduitPaquetDAO prodpaqDAO = new ProduitPaquetDAO();
        int id_paq = pDAO.FindPaquetByNom(cmbNomPaquet.getSelectedItem().toString()).getIdPaquet();
        prodpaq.setIdPaquet(id_paq);
        String date_format = "yyyy-MM-dd";
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(date_format);
        String dt = sdf.format(cal.getTime());
        prodpaq.setDateAjout(dt);

        prodpaq.setIdProd((Integer) tableProduit.getValueAt(tableProduit.getSelectedRow(), 0));
        boolean test = prodpaqDAO.insertProduitPaquet(prodpaq);

        if (test) {
            JOptionPane.showMessageDialog(this, "Produit ajouté avec succès.");
        } else {
            JOptionPane.showMessageDialog(this, "Problème d'ajout");
        }


    }//GEN-LAST:event_btnvaliderActionPerformed

    private void tablecommKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablecommKeyReleased
        textComm.setText(tablecomm.getValueAt(tablecomm.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tablecommKeyReleased

    private void tablecommKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablecommKeyPressed
        // TODO add your handling code here:
        textComm.setText(tablecomm.getValueAt(tablecomm.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tablecommKeyPressed

    private void tablecommMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecommMousePressed
        // TODO add your handling code here:
        textComm.setText(tablecomm.getValueAt(tablecomm.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tablecommMousePressed

    private void tfNomProduitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomProduitKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfNomProduitKeyTyped

    private void tfNomProduitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomProduitKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfNomProduitKeyPressed

    private void tfNomProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomProduitKeyReleased
        // TODO add your handling code here:
        String s = tfNomProduit.getText();
        if(!s.equals("")){
        MyTableProduitPrest modelprod = new MyTableProduitPrest(id_prest,s);
        tableProduit.setModel(modelprod);
        tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
            tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);
            tableProduit.repaint();
        }
        else
        {
            MyTableProduitPrest modelprod = new MyTableProduitPrest(id_prest);
        tableProduit.setModel(modelprod);
        tableProduit.getColumnModel().getColumn(0).setMinWidth(0);
            tableProduit.getColumnModel().getColumn(0).setMaxWidth(0);
            tableProduit.repaint();
        }
    }//GEN-LAST:event_tfNomProduitKeyReleased

    private void TFnOMpaquetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFnOMpaquetKeyReleased
        // TODO add your handling code here:
        String s = TFnOMpaquet.getText();
        if(!s.equals("")){
        TableListPaquetModel modelpaq = new TableListPaquetModel(id_prest,s);
        tablePaquet.setModel(modelpaq);
        tablePaquet.getColumnModel().getColumn(0).setMinWidth(0);
            tablePaquet.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePaquet.repaint();
        }
        else
        {
            TableListPaquetModel modelpaq = new TableListPaquetModel(id_prest);
        tablePaquet.setModel(modelpaq);
        tablePaquet.getColumnModel().getColumn(0).setMinWidth(0);
            tablePaquet.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePaquet.repaint();
        }
    }//GEN-LAST:event_TFnOMpaquetKeyReleased

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
               Connection connection;
        try {
            // - Connexion à la base
            connection = MySQLConnexion.getInstance();
            // - Chargement et compilation du rapport (charger le fichier jrxml déjà généré)
            URL url = getClass().getResource("paquet.jrxml");

            JasperDesign jasperDesign = JRXmlLoader.load(url.getPath());
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            // - Paramètres à envoyer au rapport
            Map parameters = new HashMap();
            parameters.put("Titre", "Titre");

            parameters.put("idPrest", 1);

            // - Execution du rapport
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, connection);

            // - Création du rapport au format PDF
            JasperExportManager.exportReportToPdfFile(jasperPrint, "paquet.pdf");
            System.out.println("success");
        } catch (JRException e) {
            System.out.println("erreur de compilation" + e.getMessage());
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspacePrest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspacePrest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspacePrest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspacePrest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } catch (Exception e) {
            //TODO exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspacePrest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjouterPanier;
    private javax.swing.JButton BtnModifierProfil;
    private javax.swing.JComboBox CmbCategori;
    private javax.swing.JLabel LabAdr;
    private javax.swing.JLabel LabCateg;
    private javax.swing.JLabel LabCateg1;
    private javax.swing.JLabel LabDesc;
    private javax.swing.JLabel LabImagePres;
    private javax.swing.JLabel LabPremium;
    private javax.swing.JLabel LabSpec;
    private javax.swing.JLabel LabSpec1;
    private javax.swing.JLabel LabTelFix;
    private javax.swing.JLabel LabTelMobile;
    private javax.swing.JLabel LabVille;
    private javax.swing.JTextField TFnOMpaquet;
    private javax.swing.JButton btnAjoutPaquet;
    private javax.swing.JButton btnAjoutProd;
    private javax.swing.JButton btnAjoutProdPaq;
    private javax.swing.JButton btnModifPaquet;
    private javax.swing.JButton btnModifProduit;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnSuppPaquet;
    private javax.swing.JButton btnSuppProduit;
    private javax.swing.JButton btnvalider;
    private javax.swing.JComboBox cmbNomPaquet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlab;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labemail;
    private javax.swing.JTable tablePaquet;
    private javax.swing.JTable tableProduit;
    private javax.swing.JTable tablecomm;
    private javax.swing.JTextPane textComm;
    private javax.swing.JTextField tfNomProduit;
    // End of variables declaration//GEN-END:variables
}
