/*
 * Copyright (C) 2014 Karim
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package tn.mariages.gui;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.dao.AdminDAO;
import tn.mariages.dao.ClientDAO;
import tn.mariages.entities.Client;
import tn.mariages.util.FTPFileUploader;

/**
 *
 * @author Karim
 */
public class InscriptionClient extends javax.swing.JFrame {
        JFileChooser fc = new JFileChooser();

    /**
     * Creates new form InscriptionClient
     */
    public InscriptionClient() {
        try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
            UIManager.put("RootPane.setupButtonVisible", false);

    }
    catch(Exception e)
    {
        //TODO exception
    }
        initComponents();
          this.setResizable(false);
        this.setLocationRelativeTo(null);
         Date d1=new Date();
     
        jDateChooser1.setDate(d1);
          jDateChooser2.setDate(d1);
      
          

        
    }
 String[] ville={"Ariana","Mannouba","Carthage","El ghazela"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPrenomMari = new javax.swing.JTextField();
        tfPrenomEpouse = new javax.swing.JTextField();
        tfNom = new javax.swing.JTextField();
        tfEmailClient = new javax.swing.JTextField();
        tfTelClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfPwdClient = new javax.swing.JPasswordField();
        cmbVilleClient = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        tfImageclient = new javax.swing.JTextField();
        btParcourir = new javax.swing.JButton();
        spinBudget = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnInscrire = new javax.swing.JButton();
        erreurPrenomMari = new javax.swing.JLabel();
        erreurPrenomEpouse = new javax.swing.JLabel();
        errerueNomFamille = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        erreurEmail = new javax.swing.JLabel();
        erreurMdp = new javax.swing.JLabel();
        erreurMdp1 = new javax.swing.JLabel();
        erreurVille = new javax.swing.JLabel();
        erreurTel = new javax.swing.JLabel();
        erreurBudget = new javax.swing.JLabel();
        erreurDate = new javax.swing.JLabel();
        erreurImage = new javax.swing.JLabel();
        tfPwdClient1 = new javax.swing.JPasswordField();
        btnQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscription", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setText("Prenom du mari");

        jLabel3.setText("Prenom de l'épouse");

        jLabel4.setText("Nom de famille");

        jLabel5.setText("E-mail ");

        jLabel6.setText("Mot De Passe");

        tfPrenomMari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrenomMariActionPerformed(evt);
            }
        });
        tfPrenomMari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrenomMariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrenomMariFocusLost(evt);
            }
        });
        tfPrenomMari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrenomMariKeyReleased(evt);
            }
        });

        tfPrenomEpouse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrenomEpouseFocusLost(evt);
            }
        });

        tfNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomFocusLost(evt);
            }
        });

        tfEmailClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailClientFocusLost(evt);
            }
        });

        tfTelClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelClientFocusLost(evt);
            }
        });

        jLabel7.setText("Telephone");

        jLabel8.setText("Ville");

        jLabel9.setText("Budget (DT)");

        jLabel10.setText("Date Du mariage");

        jLabel11.setText("Debut:");

        jLabel12.setText("Fin:");

        tfPwdClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPwdClientFocusLost(evt);
            }
        });

        jLabel13.setText("Image:");

        tfImageclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImageclientActionPerformed(evt);
            }
        });
        tfImageclient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfImageclientFocusLost(evt);
            }
        });

        btParcourir.setText("Parcourir");
        btParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirActionPerformed(evt);
            }
        });

        spinBudget.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinBudgetFocusLost(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        btnInscrire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/circle_ok.png"))); // NOI18N
        btnInscrire.setText("S'inscrire");
        btnInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrireActionPerformed(evt);
            }
        });

        erreurPrenomMari.setForeground(new java.awt.Color(255, 0, 0));

        erreurPrenomEpouse.setForeground(new java.awt.Color(255, 0, 0));

        errerueNomFamille.setForeground(new java.awt.Color(255, 0, 0));

        jLabel16.setText("Retapez mot de passe");

        erreurEmail.setForeground(new java.awt.Color(255, 0, 0));

        erreurMdp.setForeground(new java.awt.Color(255, 0, 0));

        erreurMdp1.setForeground(new java.awt.Color(255, 0, 0));

        erreurVille.setForeground(new java.awt.Color(255, 0, 0));

        erreurTel.setForeground(new java.awt.Color(255, 0, 0));

        erreurBudget.setForeground(new java.awt.Color(255, 0, 0));

        erreurDate.setForeground(new java.awt.Color(255, 0, 0));
        erreurDate.setText(" ");

        erreurImage.setForeground(new java.awt.Color(255, 0, 0));

        tfPwdClient1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPwdClient1FocusLost(evt);
            }
        });

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuitter)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPwdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPrenomMari, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfPrenomEpouse, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erreurPrenomEpouse, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errerueNomFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurPrenomMari, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(erreurDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(erreurTel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(spinBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(erreurBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfImageclient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btParcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(erreurImage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbVilleClient, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPwdClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erreurVille, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(erreurPrenomMari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erreurTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfPrenomMari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(tfTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(erreurPrenomEpouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPrenomEpouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(spinBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erreurBudget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(erreurDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errerueNomFamille))
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfImageclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btParcourir)
                            .addComponent(erreurImage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(erreurMdp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(erreurEmail))
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPwdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(tfPwdClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(erreurMdp1)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVilleClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(erreurVille))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnInscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitter)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrenomMariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrenomMariActionPerformed
        String chemin="";

        JFileChooser fc = new JFileChooser();

        int retval = fc.showOpenDialog(null);

        if (retval == JFileChooser.APPROVE_OPTION) {

            chemin = fc.getSelectedFile().getAbsolutePath();

            chemin = chemin.replace("\\", "/");    }                                            

                tfImageclient.setText(chemin);
    }//GEN-LAST:event_tfPrenomMariActionPerformed

    private void btParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirActionPerformed

        String chemin="";


        int retval = fc.showOpenDialog(null);

        if (retval == JFileChooser.APPROVE_OPTION) {

            chemin = fc.getSelectedFile().getAbsolutePath();

            chemin = chemin.replace("\\", "/");    }                                            

                tfImageclient.setText(chemin);
    }//GEN-LAST:event_btParcourirActionPerformed

    private void btnInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrireActionPerformed
Pattern pattern2 = Pattern.compile("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+" );  
    Pattern pattern = Pattern.compile("^\\d+$");
    Matcher matcher3 = pattern2.matcher(tfEmailClient.getText());
      Matcher matcher = pattern.matcher(tfTelClient.getText());
         Matcher matcher2 = pattern.matcher(spinBudget.getText());   
      
         ClientDAO clientDao=new ClientDAO();
         AdminDAO adminDAO=new AdminDAO();
         PrestataireDAO prestataireDAO=new PrestataireDAO();
        if(tfPrenomMari.getText().equals("")|| tfPrenomEpouse.getText().equals("")|| tfNom.getText().equals("") ||jDateChooser1.getDateFormatString().equals("")|| jDateChooser2.getDateFormatString().equals("")|| tfImageclient.getText().equals("") || tfEmailClient.getText().equals("") || tfPwdClient.getText().equals("")||!matcher.matches()||!matcher2.matches()||!matcher3.matches()|| clientDao.findClientByEmailBoolean(tfEmailClient.getText())|| prestataireDAO.findPrestByEmailBoolean(tfEmailClient.getText())||adminDAO.findAdminByEmailBoolean(tfEmailClient.getText()) ){
    
     String ch="";
           if(tfPrenomMari.getText().equals(""))
              erreurPrenomMari.setVisible(true);
           
            if(tfPrenomEpouse.getText().equals(""))
               erreurPrenomEpouse.setVisible(true);
            if(tfNom.getText().equals(""))
              errerueNomFamille.setVisible(true);
          
          
            if(tfEmailClient.getText().equals(""))
            { erreurEmail.setText("Ce champs ne peut pas etre vide");
              erreurEmail.setVisible(true);}
             else if(!matcher3.matches())
             {  erreurEmail.setText("Veuillez saisir un email valide");
             erreurEmail.setVisible(true);}
             
             else if(clientDao.findClientByEmailBoolean(tfEmailClient.getText())|| prestataireDAO.findPrestByEmailBoolean(tfEmailClient.getText())||adminDAO.findAdminByEmailBoolean(tfEmailClient.getText()) ){
              erreurEmail.setText("Cet email existe Deja");
             erreurEmail.setVisible(true);}
             
             
            
            
             if(spinBudget.getText().equals("")){
                 erreurBudget.setText("Ce champs ne peut pas etre vide");
               erreurBudget.setVisible(true);
               
             }
             else if(!matcher2.matches()){
             erreurBudget.setText("le budget que vous avez saisi n'est pas valide");
             erreurBudget.setVisible(true);
             }
             if(tfTelClient.getText().equals(""))
             {
              erreurTel.setText("Ce champs ne peut pas etre vide");
               erreurTel.setVisible(true);
             }
             else if(!matcher.matches())
             {
              erreurTel.setText("Le numero n'est pas valide");
               erreurTel.setVisible(true);
             }
              if(tfPwdClient.getText().equals(""))
               erreurMdp.setVisible(true);
           
              if(tfPwdClient1.getText().equals(""))
               erreurMdp1.setVisible(true);
              
              
               if(tfPwdClient1.getText().equals(""))
               {
                   erreurMdp1.setText("Ce champs ne peut pas etre vide");
               erreurMdp1.setVisible(true);
               }
               else if(!tfPwdClient1.getText().equals(tfPwdClient.getText()) && !tfPwdClient1.getText().equals("")){
                 erreurMdp1.setText("Les deux mot de passes sont differents ");
               erreurMdp1.setVisible(true);
               
               }
               
               else if(!tfPwdClient1.getText().equals(tfPwdClient.getText()) && tfPwdClient1.getText().equals("")){
               erreurMdp1.setVisible(false);
               }
                
               
               
               
              if(jDateChooser2.getDateFormatString().equals("") )
               erreurDate.setVisible(true);
             if(tfImageclient.getText().equals(""))
               erreurImage.setVisible(true);
              
         
     
     
     
     
     
     
 }else{
     
    
     
     String prMari=tfPrenomMari.getText();
 
            String prEpouse=tfPrenomEpouse.getText();
          String nom=tfNom.getText();
          String email=tfEmailClient.getText();
          String pwd=tfPwdClient.getText();
          String tel=tfTelClient.getText();
          String vville=cmbVilleClient.getSelectedItem().toString();
          int  budget= Integer.parseInt(spinBudget.getText());
          
    MessageDigest md = null;
    try {
        md = MessageDigest.getInstance("SHA-1");
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }
        ByteArrayInputStream fis = new ByteArrayInputStream(pwd.getBytes());

        byte[] dataBytes = new byte[1024];

        int nread = 0; 
    try {
        while ((nread = fis.read(dataBytes)) != -1) {
            md.update(dataBytes, 0, nread);
        }
    } catch (IOException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }

        byte[] mdbytes = md.digest();

        //convert the byte to hex format method 1
        StringBuffer pwd1 = new StringBuffer();
        for (int i = 0; i < mdbytes.length; i++) {
          pwd1.append(Integer.toString((mdbytes[i] & 0xff) + 0x100, 16).substring(1));
        }

    
      
    

         java.util.Date utilDate = jDateChooser1.getDate();
java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
             java.util.Date utilDate2 = jDateChooser2.getDate();
   java.sql.Date sqlDate2 = new java.sql.Date(utilDate2.getTime()); 
         
          String dateFin=jDateChooser2.toString();
          String img;
            System.out.println("date"+dateFin);
          Client client=new Client();
          client.setPrenomMari(prMari);
          client.setPrenomEpouse(prEpouse);
          client.setNomDeFamille(nom);
         client.setEmailClient(email);
         client.setPwdClient(pwd1.toString());
         client.setTelClient(tel);;
         client.setVilleClient(vville);
         client.setBudget(budget);
       client.setDateDebut(sqlDate.toString());
        client.setDateFin(sqlDate2.toString());
        
        
            try {
                FTPFileUploader.getInstance().UploadPic(fc.getSelectedFile().getAbsolutePath(), "/client/");
            } catch (IOException ex) {
                Logger.getLogger(AjoutClient.class.getName()).log(Level.SEVERE, null, ex);
            }
             img = "http://mariages.tn/client/"+fc.getSelectedFile().getName();
        client.setImgClient(img);
        
         clientDao.insertClient(client);
            EspaceClient espace=new EspaceClient(clientDao.findClientByEmail(email).getIdClient(), "c");
            this.dispose();
            espace.setVisible(true);
            
            
          
 }              
          
    }//GEN-LAST:event_btnInscrireActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
 for (int i=0;i<ville.length;i++){
                 cmbVilleClient.addItem(ville[i]);
                 
             }
    }//GEN-LAST:event_formWindowOpened

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
//Authentication auth =new Authentication();
//auth.setVisible(true);
        Login log = new Login();
        log.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void tfPrenomMariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrenomMariKeyReleased
         
    }//GEN-LAST:event_tfPrenomMariKeyReleased

    private void tfPrenomMariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrenomMariFocusLost
if(!tfPrenomMari.getText().equals(""))      
           erreurPrenomMari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
else
     erreurPrenomMari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
    }//GEN-LAST:event_tfPrenomMariFocusLost

    private void tfPrenomMariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrenomMariFocusGained
        
    }//GEN-LAST:event_tfPrenomMariFocusGained

    private void tfPrenomEpouseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrenomEpouseFocusLost
      if(!tfPrenomEpouse.getText().equals(""))
           erreurPrenomEpouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
else
     erreurPrenomEpouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        
    }//GEN-LAST:event_tfPrenomEpouseFocusLost

    private void tfNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomFocusLost
   if(!tfNom.getText().equals(""))
         errerueNomFamille.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
else
     errerueNomFamille.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
    }//GEN-LAST:event_tfNomFocusLost

    private void tfEmailClientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailClientFocusLost
     ClientDAO clientDao=new ClientDAO();
         AdminDAO adminDAO=new AdminDAO();
         PrestataireDAO prestataireDAO=new PrestataireDAO();
         Pattern pattern2 = Pattern.compile("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+" );  
         Matcher matcher3 = pattern2.matcher(tfEmailClient.getText());
         if(tfEmailClient.getText().equals(""))
               erreurEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            else if((clientDao.findClientByEmailBoolean(tfEmailClient.getText())|| prestataireDAO.findPrestByEmailBoolean(tfEmailClient.getText())||adminDAO.findAdminByEmailBoolean(tfEmailClient.getText()) ))
                   erreurEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
              else if(!matcher3.matches())
                     erreurEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
         else
                     erreurEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
    }//GEN-LAST:event_tfEmailClientFocusLost

    private void tfPwdClientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPwdClientFocusLost
         if(!tfPwdClient.getText().equals(""))
                erreurMdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
         else
               erreurMdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
    }//GEN-LAST:event_tfPwdClientFocusLost

    private void tfPwdClient1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPwdClient1FocusLost
           if(tfPwdClient1.getText().equals(""))
               {
                     erreurMdp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
               }
               else if(!tfPwdClient1.getText().equals(tfPwdClient.getText()) && !tfPwdClient1.getText().equals("")){
                 erreurMdp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
               
               }
           else
                      erreurMdp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
    }//GEN-LAST:event_tfPwdClient1FocusLost

    private void tfTelClientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelClientFocusLost
  Pattern pattern = Pattern.compile("^[0-9]{8}+$");
   Matcher matcher = pattern.matcher(tfTelClient.getText());
    if(tfTelClient.getText().equals(""))
             {
               erreurTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else if(!matcher.matches())
             {
             erreurTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else{
                    erreurTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
             }
    }//GEN-LAST:event_tfTelClientFocusLost

    private void spinBudgetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinBudgetFocusLost
          Pattern pattern = Pattern.compile("^\\d+$");
   
         Matcher matcher = pattern.matcher(spinBudget.getText()); 
          if(spinBudget.getText().equals(""))
             {
               erreurBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else if(!matcher.matches())
             {
             erreurBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
             }
             else{
                   erreurBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
             }
    }//GEN-LAST:event_spinBudgetFocusLost

    private void tfImageclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImageclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfImageclientActionPerformed

    private void tfImageclientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfImageclientFocusLost
          if(!tfImageclient.getText().equals(""))
             erreurImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
          else
                erreurImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
    }//GEN-LAST:event_tfImageclientFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
            UIManager.put("RootPane.setupButtonVisible", false);

    }
    catch(Exception e)
    {
        //TODO exception
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btParcourir;
    private javax.swing.JButton btnInscrire;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox cmbVilleClient;
    private javax.swing.JLabel errerueNomFamille;
    private javax.swing.JLabel erreurBudget;
    private javax.swing.JLabel erreurDate;
    private javax.swing.JLabel erreurEmail;
    private javax.swing.JLabel erreurImage;
    private javax.swing.JLabel erreurMdp;
    private javax.swing.JLabel erreurMdp1;
    private javax.swing.JLabel erreurPrenomEpouse;
    private javax.swing.JLabel erreurPrenomMari;
    private javax.swing.JLabel erreurTel;
    private javax.swing.JLabel erreurVille;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField spinBudget;
    public javax.swing.JTextField tfEmailClient;
    public javax.swing.JTextField tfImageclient;
    public javax.swing.JTextField tfNom;
    public javax.swing.JTextField tfPrenomEpouse;
    public javax.swing.JTextField tfPrenomMari;
    private javax.swing.JPasswordField tfPwdClient;
    private javax.swing.JPasswordField tfPwdClient1;
    private javax.swing.JTextField tfTelClient;
    // End of variables declaration//GEN-END:variables
}
