/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.mariages.gui;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import tn.mariages.dao.ClientDAO;

import tn.mariages.entities.ToDo;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.dao.AdminDAO;
import tn.mariages.dao.ToDoDAO;
import tn.mariages.entities.Admin;
/**
 *
 * @author RAED
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        cbRememberMe = new javax.swing.JCheckBox();
        btnConnect = new javax.swing.JButton();
        btnMdp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Email :");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Mot de passe");

        tfPwd.setText("jPasswordField1");
        tfPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPwdFocusGained(evt);
            }
        });

        cbRememberMe.setText("Remember me");
        cbRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRememberMeActionPerformed(evt);
            }
        });

        btnConnect.setText("Se connecter");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnMdp.setText("Mot de passe oublié");
        btnMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbRememberMe)
                    .addComponent(tfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(tfEmail))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMdp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConnect)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbRememberMe)
                .addGap(18, 18, 18)
                .addComponent(btnConnect)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void cbRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRememberMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRememberMeActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
     
         String email=tfEmail.getText();
        String pwd=tfPwd.getText();
         
        if(cbRememberMe.isSelected()){
        File file = new File("email.txt");   
         File file2 = new File("Pass.txt");   
     
         
         
  FileWriter fw = null;   

                FileWriter fw2 = null;   
 
        try {   
            //Création de l'objet   
            fw = new FileWriter(file);
            fw2 = new FileWriter(file2);   
        } catch (IOException ex) {   
            System.out.println("ko");
        }   
   
                          
        try {   
            //On écrit la chaîne   
            fw.write(email);   
            fw2.write(pwd);   
        } catch (IOException ex) {   
            System.out.println("probleme");
        }
        
         try {   
            //On ferme le flux   
            fw.close();   
            fw2.close();   
        } catch (IOException ex) {   
           
        }    
        
        }

        
        
        ClientDAO clientDAO=new ClientDAO();
        PrestataireDAO prestatiareDAO=new PrestataireDAO();
        AdminDAO adminDAO=new AdminDAO();
        if(adminDAO.connectAdmin(email, pwd)){
        
       dispose();
       Accueil accueil=new Accueil();
       accueil.setVisible(true);
        }
        else if(clientDAO.connectClient(email, pwd)){
            ToDoDAO todoDAO=new ToDoDAO();
            todoDAO.DeleteToDos(clientDAO.findClientByEmail(email).getIdClient());
            List <ToDo> listeTodo=new ArrayList<ToDo>();
            listeTodo=todoDAO.NotifyClient(clientDAO.findClientByEmail(email).getIdClient());
            String notify="N'oubliez pas les choses a faire demain : \n\n";
            for (ToDo toDo : listeTodo) {
                notify+="Titre : "+toDo.getTitreToDo()+"\n";
                   notify+="Description : "+toDo.getDescToDo()+"\n\n";
                   
            }
            int dialogButton = JOptionPane.OK_CANCEL_OPTION;
            
                JOptionPane.showConfirmDialog (null,notify,"Rappel",dialogButton);
         dispose();
       Accueil accueil=new Accueil();
       accueil.setVisible(true);
        
        }
        
        else if(prestatiareDAO.connectPrestataire(email, pwd))
        {  
            dispose();
       Accueil accueil=new Accueil();
       accueil.setVisible(true);
        }
        else{
         int dialogButton = JOptionPane.OK_OPTION;
          JOptionPane.showConfirmDialog (null, "L'email ou le mot de passe saisi est invalide","ERROR",dialogButton);
        
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void tfPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPwdFocusGained
        tfPwd.setText("");
    }//GEN-LAST:event_tfPwdFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String email1="";
String pwd1="";
int pwd2=0;
File f1=new File("email.txt");
File f2=new File("Pass.txt");
       Scanner lecteur=null;
       Scanner lecteur1=null;
        try {
            lecteur = new Scanner(f1);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (lecteur.hasNext()){
        email1=lecteur.next();
        }
            
        


  try {
            lecteur1 = new Scanner(f2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (lecteur1.hasNext()){
       pwd1=lecteur1.next();
        }
        
          // TODO add your handling code here:
      tfEmail.setText(email1);
      tfPwd.setText(pwd1);


    }//GEN-LAST:event_formWindowOpened

    private void btnMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMdpActionPerformed
MotDePasseOublié mdp=new MotDePasseOublié();
mdp.setVisible(true);
    }//GEN-LAST:event_btnMdpActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnMdp;
    private javax.swing.JCheckBox cbRememberMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
