package tn.mariages.gui;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;
import tn.mariages.dao.ClientDAO;

import tn.mariages.entities.ToDo;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.dao.AdminDAO;
import tn.mariages.dao.ToDoDAO;
import tn.mariages.entities.Client;
import tn.mariages.entities.Prestataire;
import static tn.mariages.gui.FacebookLoginTEST.access_token;
import static tn.mariages.gui.FacebookLoginTEST.firstRequest;
import static tn.mariages.gui.FacebookLoginTEST.firstRequestDone;
import static tn.mariages.gui.FacebookLoginTEST.secondRequest;
import static tn.mariages.gui.FacebookLoginTEST.secondRequestDone;
import tn.mariages.util.facebook.GraphReaderExample;
/**
 *
 * @author RAED
 */
public class Login extends javax.swing.JFrame {

     
  public static String API_KEY = "1422860571264717";
  public static String SECRET = "263401ccd735a71496a83d4c8b9e8425";

  public static String firstRequest = "https://graph.facebook.com/oauth/authorize?"
  + "client_id="
  + API_KEY
  + "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
  + "scope=publish_stream,offline_access,create_event,read_stream,email,user_birthday";
  
  public static String secondRequest="https://graph.facebook.com/oauth/access_token?"
  + "client_id="
  + API_KEY
  + "&redirect_uri=http://www.facebook.com/connect/login_success.html&"
  + "client_secret=" + SECRET + "&code=";

  public static String access_token = "CAAUOFYrqRs0BAPNdYRxuXVrZBNQ7gIM5iNnAJw92pVglOlSCUd25DRdhQ1AZAwRKPZAZCpUIKIxZCYIhD8CIZCgGhqrlYdyJujOyrhRPitOMp3SG1DmkchoDZABXN7QtUTK9BDCDqpcBzcPqxdqhE4WEX6qGYOoGzY0F2GVtyybJtt6529EF3ny";
  public static boolean firstRequestDone = false;
  public static boolean secondRequestDone = false; 
   
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        cbRememberMe = new javax.swing.JCheckBox();
        btnConnect = new javax.swing.JButton();
        btnInscriClient = new javax.swing.JButton();
        btnInscriPrest = new javax.swing.JButton();
        btnMdp = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("E-mail ");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Mot de passe");

        tfPwd.setText("jPasswordField1");
        tfPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPwdFocusGained(evt);
            }
        });

        cbRememberMe.setText("Remember me");
        cbRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRememberMeActionPerformed(evt);
            }
        });

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/signup.png"))); // NOI18N
        btnConnect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnInscriClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/user_circle.png"))); // NOI18N
        btnInscriClient.setToolTipText("Inscription Client");
        btnInscriClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriClientActionPerformed(evt);
            }
        });

        btnInscriPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/tag.png"))); // NOI18N
        btnInscriPrest.setToolTipText("Inscription Prestataire");
        btnInscriPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriPrestActionPerformed(evt);
            }
        });

        btnMdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/cog.png"))); // NOI18N
        btnMdp.setText("Mot de passe oublié");
        btnMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMdpActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/inf_hurt.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tn/mariages/util/facebook/img/facebook_login.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRememberMe)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInscriClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInscriPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMdp)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConnect)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Logo)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRememberMe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInscriClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInscriPrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void cbRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRememberMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRememberMeActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
     
         String email=tfEmail.getText();
        String pwd=tfPwd.getText();
         
        if(cbRememberMe.isSelected()){
        File file = new File("email.txt");   
         File file2 = new File("Pass.txt");   
     
         
         
  FileWriter fw = null;   

                FileWriter fw2 = null;   
 
        try {   
            //Création de l'objet   
            fw = new FileWriter(file);
            fw2 = new FileWriter(file2);   
        } catch (IOException ex) {   
            System.out.println("ko");
        }   
   
                          
        try {   
            //On écrit la chaîne   
            fw.write(email);   
            fw2.write(pwd);   
        } catch (IOException ex) {   
            System.out.println("probleme");
        }
        
         try {   
            //On ferme le flux   
            fw.close();   
            fw2.close();   
        } catch (IOException ex) {   
           
        }    
        
        }

        
         MessageDigest md = null;
    try {
        md = MessageDigest.getInstance("SHA-1");
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }
        ByteArrayInputStream fis = new ByteArrayInputStream(pwd.getBytes());

        byte[] dataBytes = new byte[1024];

        int nread = 0; 
    try {
        while ((nread = fis.read(dataBytes)) != -1) {
            md.update(dataBytes, 0, nread);
        }
    } catch (IOException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }

        byte[] mdbytes = md.digest();

        //convert the byte to hex format method 1
        StringBuffer pwd1 = new StringBuffer();
        for (int i = 0; i < mdbytes.length; i++) {
          pwd1.append(Integer.toString((mdbytes[i] & 0xff) + 0x100, 16).substring(1));
        }
        
        
        
        
        
        ClientDAO clientDAO=new ClientDAO();
        PrestataireDAO prestatiareDAO=new PrestataireDAO();
        AdminDAO adminDAO=new AdminDAO();
        
        if(adminDAO.connectAdmin(email, pwd1.toString())){
        
       dispose();
       Accueil accueil=new Accueil();
       accueil.setVisible(true);
        }
        else if(clientDAO.connectClient(email, pwd1.toString())){
            Client c = clientDAO.findClientByEmail(email);
            ToDoDAO todoDAO=new ToDoDAO();
            todoDAO.DeleteToDos(clientDAO.findClientByEmail(email).getIdClient());
         
           
         dispose();

         EspaceClient EC = new EspaceClient(c.getIdClient(), "c");
         EC.setVisible(true);
        
        }
        
        else if(prestatiareDAO.connectPrestataire(email, pwd1.toString()))
        {  
            dispose();
             Prestataire findPrestByEmail = prestatiareDAO.findPrestByEmail(email);
      EspacePrest EP = new EspacePrest(findPrestByEmail.getIdPrest(), "p");
      EP.setVisible(true);
        }
        else{
         int dialogButton = JOptionPane.OK_OPTION;
          JOptionPane.showConfirmDialog (null, "L'email ou le mot de passe saisi est invalide","ERROR",dialogButton);
        
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void tfPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPwdFocusGained
        tfPwd.setText("");
    }//GEN-LAST:event_tfPwdFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               btnConnect.setBorder(BorderFactory.createEmptyBorder());
               jButton1.setBorder(BorderFactory.createEmptyBorder());

        String email1="";
String pwd1="";
int pwd2=0;
File f1=new File("email.txt");
File f2=new File("Pass.txt");
       Scanner lecteur=null;
       Scanner lecteur1=null;
        try {
            lecteur = new Scanner(f1);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (lecteur.hasNext()){
        email1=lecteur.next();
        }
            
        


  try {
            lecteur1 = new Scanner(f2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (lecteur1.hasNext()){
       pwd1=lecteur1.next();
        }
        
          // TODO add your handling code here:
      tfEmail.setText(email1);
      tfPwd.setText(pwd1);

      
            
             NativeInterface.open();
                NativeInterface.initialize();
    }//GEN-LAST:event_formWindowOpened

    private void btnMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMdpActionPerformed
MotDePasseOublie mdp=new MotDePasseOublie();
mdp.setVisible(true);
    }//GEN-LAST:event_btnMdpActionPerformed

    private void btnInscriClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriClientActionPerformed
      this.dispose();
      InscriptionClient inscriClient=new InscriptionClient();
      inscriClient.setVisible(true);
    }//GEN-LAST:event_btnInscriClientActionPerformed

    private void btnInscriPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriPrestActionPerformed
       this.dispose();
               
        InscriptionPrestataire inscriPrest=new InscriptionPrestataire();
       inscriPrest.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inscriPrest.setVisible(true);
    }//GEN-LAST:event_btnInscriPrestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        final JFrame authFrame = new JFrame();
       
    // Create the JWebBrowser and add the WebBrowserAdapter
    JPanel webBrowserPanel = new JPanel(new BorderLayout());
    final JWebBrowser webBrowser = new JWebBrowser();
    webBrowser.navigate(firstRequest);
    webBrowser.addWebBrowserListener(new WebBrowserAdapter() {
      @Override
      public void locationChanged(WebBrowserNavigationEvent e) {
        super.locationChanged(e);
        // Check if first request was not done
        if (!firstRequestDone) {
          // Check if you left the location and were redirected to the next 
          // location
          if (e.getNewResourceLocation().contains("http://www.facebook.com/connect/login_success.html?code=")){
            // If it successfully redirects you, get the verification code
            // and go for a second request
            String[] splits = e.getNewResourceLocation().split("=");
            String stage2temp = secondRequest + splits[1];
            webBrowser.navigate(stage2temp);
            firstRequestDone = true;
          }
        } else {
          // If secondRequest is not done yet, you perform this and get the 
          // access_token
          if (!secondRequestDone) {
            System.out.println(webBrowser.getHTMLContent());
            // Create reader with the html content
            StringReader readerSTR = new StringReader(webBrowser.getHTMLContent());
            // Create a callback for html parser
            HTMLEditorKit.ParserCallback callback = 
            new HTMLEditorKit.ParserCallback() {
              public void handleText(char[] data,int pos) {
                System.out.println(data);
                // because there is only one line with the access_token 
                // in the html content you can parse it.
                String string = new String(data);
                String[] temp1 = string.split("&");
                String[] temp2 = temp1[0].split("=");
                access_token = temp2[1];
              }
            };
            try {
              // Call the parse method 
              new ParserDelegator().parse(readerSTR,callback,false);
            } catch (IOException e1) {
              e1.printStackTrace();
            }
            // After everything is done, you can dispose the jframe
            authFrame.dispose();      
         
            
            GraphReaderExample gre = new GraphReaderExample(access_token);
                    List<String> user = gre.getUSER();
                    ClientDAO cDAO = new ClientDAO();
                    Client C = new Client();
                    System.out.println("EMAIL "+user.get(3));
                    if(cDAO.findClientByEmailBoolean(user.get(3)))
                    {
                        
                        EspaceClient EC = new EspaceClient(cDAO.findClientByEmail(user.get(3)).getIdClient(),"c");
                        EC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        EC.setVisible(true);
                        
                    }
                    else
                    {
                        InscriptionClient insC = new InscriptionClient();
                        insC.tfImageclient.setText("https://graph.facebook.com/"+user.get(0)+"?fields=picture.width(720).height(720) ");
                        insC.tfEmailClient.setText(user.get(3));
                        insC.tfNom.setText(user.get(2));
                        if(user.get(6).equals("male"))
                        {
                            insC.tfPrenomMari.setText(user.get(1));
                        }
                        else if(!user.get(6).equals("male") && user.get(6)!=null)
                        {
                            insC.tfPrenomEpouse.setText(user.get(1));
                        }
                        insC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                         insC.setVisible(true);
                    }
//                    for (int i = 0; i < user.size(); i++) {
//                        System.out.println(user.get(i)+"\n");
//                   }

          }
        }
      }
    });
     this.dispose();
    webBrowserPanel.add(webBrowser,BorderLayout.CENTER);
    authFrame.add(webBrowserPanel);
    authFrame.setSize(400, 500);
    authFrame.setVisible(true);
  
        

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//try
//    {
//        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
//            UIManager.put("RootPane.setupButtonVisible", false);
//
//    }
//    catch(Exception e)
//    {
//        //TODO exception
//    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnInscriClient;
    private javax.swing.JButton btnInscriPrest;
    private javax.swing.JButton btnMdp;
    private javax.swing.JCheckBox cbRememberMe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
