/*
 * Copyright (C) 2014 Youssef
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package tn.mariages.gui;

import aurelienribon.dialogdemo.MyDialog;
import aurelienribon.dialogdemo.SwingUtils;
import com.alee.laf.WebLookAndFeel;
import java.awt.Image;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.dao.ProduitDAO;
import tn.mariages.entities.Prestataire;
import tn.mariages.entities.Produit;
import tn.mariages.util.FTPFileUploader;

/**
 *
 * @author Youssef
 */
public class ModifierProduit extends javax.swing.JFrame {

    String[] Categories = {"--Choisir catégorie--", "La mariée", "le mari", "Beauté", "La réception", "Gastronomie", "Annimation", "Voyages", "Photographe"};
    int id;
    Produit p = new Produit();
    private int id_prest;

    /**
     *
     * Creates new form AjoutProduit
     */
    public ModifierProduit() {

        initComponents();
    }

    public ModifierProduit(int id) {
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfnomProduit = new javax.swing.JTextField();
        tfPrixProduit = new javax.swing.JTextField();
        cmbCategorieProduit = new javax.swing.JComboBox();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescProduit = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cmbPrestataire = new javax.swing.JComboBox();
        btnmaj = new javax.swing.JButton();
        webFileDrop1 = new com.alee.extended.filechooser.WebFileDrop();
        webFileDrop2 = new com.alee.extended.filechooser.WebFileDrop();
        erreurnomP = new javax.swing.JLabel();
        erreurDes = new javax.swing.JLabel();
        erreurPres = new javax.swing.JLabel();
        erreurCat = new javax.swing.JLabel();
        erreurPrix = new javax.swing.JLabel();
        erreurImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setToolTipText("Modifier Produit");
        jPanel1.setMaximumSize(new java.awt.Dimension(32750, 32750));

        jLabel1.setText("Nom Du Produit :");

        jLabel2.setText("Description : ");

        jLabel3.setText("Categorie :");

        jLabel4.setText("Prix");

        jLabel5.setText("Images");

        tfnomProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomProduitActionPerformed(evt);
            }
        });
        tfnomProduit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfnomProduitFocusLost(evt);
            }
        });

        tfPrixProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrixProduitActionPerformed(evt);
            }
        });
        tfPrixProduit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrixProduitFocusLost(evt);
            }
        });

        cmbCategorieProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategorieProduitActionPerformed(evt);
            }
        });
        cmbCategorieProduit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbCategorieProduitFocusLost(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/close.png"))); // NOI18N
        btnReset.setText("Annuler");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tfDescProduit.setColumns(20);
        tfDescProduit.setRows(5);
        tfDescProduit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescProduitFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tfDescProduit);

        jLabel6.setText("Prestataire :");

        cmbPrestataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrestataireActionPerformed(evt);
            }
        });
        cmbPrestataire.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbPrestataireFocusLost(evt);
            }
        });

        btnmaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Modify-icon.png"))); // NOI18N
        btnmaj.setText("Mettre a jour");
        btnmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmajActionPerformed(evt);
            }
        });

        webFileDrop1.setBorder(new javax.swing.border.MatteBorder(null));
        webFileDrop1.setDropText("Placez vos images ici");

        webFileDrop2.setBorder(new javax.swing.border.MatteBorder(null));
        webFileDrop2.setDropText("Placez vos images ici");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnmaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbPrestataire, 0, 277, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(cmbCategorieProduit, 0, 277, Short.MAX_VALUE)
                            .addComponent(tfPrixProduit, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(webFileDrop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erreurImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(webFileDrop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(124, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(erreurPres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(erreurDes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erreurCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erreurPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfnomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erreurnomP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(tfnomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(erreurnomP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurDes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cmbPrestataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erreurPres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCategorieProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(erreurCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPrixProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(erreurPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(webFileDrop2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(erreurImg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnmaj)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(webFileDrop1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnomProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomProduitActionPerformed


    private void tfPrixProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrixProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrixProduitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed


    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbCategorieProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategorieProduitActionPerformed


    }//GEN-LAST:event_cmbCategorieProduitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        p = new ProduitDAO().DisplayProdByID(id);
        for (int i = 0; i < 7; i++) {

            cmbCategorieProduit.addItem(Categories[i]);
        }
        for (int i = 0; i < 7; i++) {
            if (p.getCategorieProd().equals(Categories[i])) {
                cmbCategorieProduit.setSelectedIndex(i);
            }
        }

        PrestataireDAO myAO = new PrestataireDAO();
        List<Prestataire> myList = new ArrayList<>();
        myList = myAO.DisplayAllPrestataire();
        for (int i = 0; i < myList.size(); i++) {
            cmbPrestataire.addItem(myList.get(i).getNomPrest());

        }
        int pres = new ProduitDAO().DisplayProdByID(this.id).getIdPrest();
        for (int i = 0; i < myList.size(); i++) {
            if (new PrestataireDAO().findPrestById(pres).getNomPrest().equals(myList.get(i).getNomPrest())) {
                cmbPrestataire.setSelectedIndex(i);
            }
        }
        DecimalFormat f = new DecimalFormat("##");
        tfnomProduit.setText(p.getNomProd());
        tfDescProduit.setText(p.getDescProd());
        tfPrixProduit.setText(String.valueOf(f.format(p.getPrixProd())));
        
    }//GEN-LAST:event_formWindowOpened

    private void cmbPrestataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrestataireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrestataireActionPerformed

    private void btnmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmajActionPerformed
        if (tfnomProduit.getText().equals("") || tfDescProduit.getText().equals("") || tfPrixProduit.getText().equals("")) {
            if (tfnomProduit.getText().equals("")) {
                erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (tfPrixProduit.getText().equals("")) {
                erreurPrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (tfDescProduit.getText().equals("")) {
                erreurDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (cmbCategorieProduit.getSelectedItem().equals("--Choisir categorie--")) {
                erreurCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (cmbPrestataire.getSelectedItem().equals("--Choisir prestataire--")) {
                erreurPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }
            if (webFileDrop1.getSelectedFiles().isEmpty()) {
                erreurImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }

        } else {
        
        
        ProduitDAO myDAO = new ProduitDAO();
        PrestataireDAO myDAO1 = new PrestataireDAO();
        Produit p = new Produit();
        String date_format = "yyyy-MM-dd";
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(date_format);
        String dt = sdf.format(cal.getTime());
        if (cmbPrestataire.isVisible()) {
            id_prest = myDAO1.findPrestByNomPrest(cmbPrestataire.getSelectedItem().toString()).getIdPrest();
        }
        p.setIdProd(id);
        p.setNomProd(tfnomProduit.getText());
        p.setCategorieProd(cmbCategorieProduit.getSelectedItem().toString());
        p.setPrixProd(Integer.parseInt(tfPrixProduit.getText()));
        p.setDescProd(tfDescProduit.getText());
        p.setShortDescProd(tfDescProduit.getText().substring(0, 10) + "...");
        p.setDateAjoutProd(dt);
        p.setIdPrest(id_prest);
        String[] images = {"\"http://placehold.it/150x150&text=Img%20Produit\"", "\"http://placehold.it/150x150&text=Img%20Produit\" ", "\"http://placehold.it/150x150&text=Img%20Produit\"", "\"http://placehold.it/150x150&text=Img%20Produit\"", "\"http://placehold.it/150x150&text=Img%20Produit\""};
            for (int i = 0; i < webFileDrop1.getSelectedFiles().size(); i++) {
                if (webFileDrop1.getSelectedFiles().get(i).getAbsolutePath() != null) {
                    try {
                        FTPFileUploader.getInstance().UploadPic(webFileDrop1.getSelectedFiles().get(0).getAbsolutePath(), "/prod/");
                    } catch (IOException ex) {
                        Logger.getLogger(AjoutProduit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    images[i] = "http://mariages.tn/prod/" + webFileDrop1.getSelectedFiles().get(i).getName();
                } else {
                    images[i] = "http://placehold.it/150x150&text=Img%20Produit";
                }
            }
            p.setImgProd_P(images[0]);
            p.setImgProd_1(images[1]);
            p.setImgProd_2(images[2]);
            p.setImgProd_3(images[3]);
            p.setImgProd_4(images[4]);
            
        myDAO.UpdateProd(p);}
    }//GEN-LAST:event_btnmajActionPerformed

    private void tfnomProduitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnomProduitFocusLost
 if (tfnomProduit.getText().equals("")) {
            erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else {
            erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomProduitFocusLost

    private void tfDescProduitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescProduitFocusLost
  if (tfDescProduit.getText().equals("")) {
            erreurnomP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else if (tfDescProduit.getText().length() < 10) {
            erreurDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        } else {
            erreurDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescProduitFocusLost

    private void tfPrixProduitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrixProduitFocusLost
 Pattern pattern = Pattern.compile("^\\d+$");
        Matcher matcher = pattern.matcher(tfPrixProduit.getText());
        if (!tfPrixProduit.getText().equals("")) {
            erreurPrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        }  else if (!matcher.matches()) {
                erreurPrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
               
            }  else{
            erreurPrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrixProduitFocusLost

    private void cmbPrestataireFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbPrestataireFocusLost
 if (cmbPrestataire.getSelectedItem().equals("--Choisir prestataire--")) {
                erreurPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }else {
            erreurPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrestataireFocusLost

    private void cmbCategorieProduitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCategorieProduitFocusLost
 if (cmbCategorieProduit.getSelectedItem().equals("--Choisir categorie--")) {
                erreurCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/erreur.jpg")));
            }else {
            erreurCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/bon.jpg")));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategorieProduitFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                javax.swing.UIManager.setLookAndFeel(WebLookAndFeel.class.getCanonicalName());
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                WebLookAndFeel.setDecorateAllWindows(true);
                new ModifierProduit().setVisible(true);

            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ImgChooser;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnmaj;
    private javax.swing.JComboBox cmbCategorieProduit;
    private javax.swing.JComboBox cmbPrestataire;
    private javax.swing.JLabel erreurCat;
    private javax.swing.JLabel erreurDes;
    private javax.swing.JLabel erreurImg;
    private javax.swing.JLabel erreurPres;
    private javax.swing.JLabel erreurPrix;
    private javax.swing.JLabel erreurnomP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tfDescProduit;
    private javax.swing.JTextField tfPrixProduit;
    private javax.swing.JTextField tfnomProduit;
    private com.alee.extended.filechooser.WebFileDrop webFileDrop1;
    private com.alee.extended.filechooser.WebFileDrop webFileDrop2;
    // End of variables declaration//GEN-END:variables

}
