/*
 * Copyright (C) 2014 RAED
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package tn.mariages.gui;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.entities.Prestataire;

/**
 *
 * @author RAED
 */
public class Modif_Prest extends javax.swing.JFrame {

     Prestataire prest=new Prestataire();
     PrestataireDAO presDAO=new PrestataireDAO();
     
    public Modif_Prest() {
        initComponents();
    }
     public Modif_Prest(Prestataire p) {
        initComponents();
        Prestataire p1=new Prestataire();
        p1=p;
        labelIdPrest.setText(""+p.getIdPrest());
        tfNomPrest.setText(p.getNomPrest());
        taDescPrest.setText(p.getDescPrest());
        taAdrPrest.setText(p.getAdrPrest());
        cmbVillePrest.addItem(p.getVillePrest());    
        tfTelFixePrest.setText(p.getTelFixePrest());
        tfTelMobilPrest.setText(p.getTelMobilePrest());
        TfEmailPrest.setText(p.getEmailPrest());
        TfPwdPrest.setText(p.getPwdPrest());
        cmbCategoriePrest.addItem(p.getCategorie());
        cmbSpecialitePrest.addItem(p.getSpecialite());
//        if(p.isCompteValide()){
       chkCmptValidePrest.setSelected(p.isCompteValide());
//        }
//        if(p.isMailValide()){
        chkEmailValidePrest.setSelected(p.isMailValide());
//        }
//        if(p.isPremium()){
       chkPremiumPrest.setSelected(p.isPremium());
//        }
      
        tfDatePayementPrest.setText(p.getDatePayement());
        labelIdPrest.setVisible(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlModifierPrest = new javax.swing.JPanel();
        tfNomPrest = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescPrest = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAdrPrest = new javax.swing.JTextArea();
        tfTelFixePrest = new javax.swing.JTextField();
        TfEmailPrest = new javax.swing.JTextField();
        TfPwdPrest = new javax.swing.JPasswordField();
        cmbVillePrest = new javax.swing.JComboBox();
        cmbCategoriePrest = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnValiderModifPrest = new javax.swing.JButton();
        btnAnulModifPrest = new javax.swing.JButton();
        ff = new javax.swing.JLabel();
        tfTelMobilPrest = new javax.swing.JTextField();
        cmbSpecialitePrest = new javax.swing.JComboBox();
        tfimage = new javax.swing.JLabel();
        tfImagePrest = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelIdPrest = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfDatePayementPrest = new JFormattedTextField(new SimpleDateFormat("dd/MM/yyyy"));
        chkCmptValidePrest = new javax.swing.JCheckBox();
        chkEmailValidePrest = new javax.swing.JCheckBox();
        chkPremiumPrest = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modifier Perstataire");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("ModifPrest"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlModifierPrest.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifier prestataire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        taDescPrest.setColumns(20);
        taDescPrest.setRows(5);
        jScrollPane1.setViewportView(taDescPrest);

        taAdrPrest.setColumns(3);
        taAdrPrest.setRows(5);
        jScrollPane2.setViewportView(taAdrPrest);

        tfTelFixePrest.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfTelFixePrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelFixePrestActionPerformed(evt);
            }
        });

        cmbVillePrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVillePrestActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Description");

        jLabel4.setText("Adresse");

        aa.setText("Tél mobil:");

        jLabel6.setText("E-mail");

        jLabel7.setText("Mot de passe");

        jLabel8.setText("Ville");

        jLabel9.setText("Catégorie");

        jLabel10.setText("Spécialité");

        btnValiderModifPrest.setBackground(new java.awt.Color(204, 204, 204));
        btnValiderModifPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Modify-icon.png"))); // NOI18N
        btnValiderModifPrest.setText("  Valider");
        btnValiderModifPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderModifPrestActionPerformed(evt);
            }
        });

        btnAnulModifPrest.setBackground(new java.awt.Color(204, 204, 204));
        btnAnulModifPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/circle_delete.png"))); // NOI18N
        btnAnulModifPrest.setText("  Anuller");
        btnAnulModifPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnulModifPrestActionPerformed(evt);
            }
        });

        ff.setText("Tel fixe:");

        tfimage.setText("Image:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modifier Prestataire");

        labelIdPrest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIdPrest.setForeground(new java.awt.Color(102, 102, 102));
        labelIdPrest.setText("00");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abonnement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tfDatePayementPrest.setToolTipText("");
        tfDatePayementPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatePayementPrestActionPerformed(evt);
            }
        });

        chkCmptValidePrest.setText("Compte Vérifié");

        chkEmailValidePrest.setText("E-mail Valide");
        chkEmailValidePrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmailValidePrestActionPerformed(evt);
            }
        });

        chkPremiumPrest.setText("Premium");
        chkPremiumPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPremiumPrestActionPerformed(evt);
            }
        });

        jLabel5.setText("Date payement:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(chkCmptValidePrest)
                        .addGap(18, 18, 18)
                        .addComponent(chkEmailValidePrest)
                        .addGap(18, 18, 18)
                        .addComponent(chkPremiumPrest))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(tfDatePayementPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCmptValidePrest)
                    .addComponent(chkEmailValidePrest)
                    .addComponent(chkPremiumPrest))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDatePayementPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jButton1.setText("Parcourir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModifierPrestLayout = new javax.swing.GroupLayout(pnlModifierPrest);
        pnlModifierPrest.setLayout(pnlModifierPrestLayout);
        pnlModifierPrestLayout.setHorizontalGroup(
            pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                        .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(56, 56, 56)
                                            .addComponent(cmbVillePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(27, 27, 27)
                                            .addComponent(cmbCategoriePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29)
                                        .addComponent(cmbSpecialitePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNomPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfimage)
                                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelIdPrest))
                                            .addComponent(jLabel3)
                                            .addComponent(aa)
                                            .addComponent(ff)))))
                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(45, 45, 45)
                                        .addComponent(TfEmailPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TfPwdPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelMobilPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                        .addComponent(tfImagePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(62, 62, 62))
                            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTelFixePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1))
                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValiderModifPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(btnAnulModifPrest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModifierPrestLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnulModifPrest, btnValiderModifPrest});

        pnlModifierPrestLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TfEmailPrest, TfPwdPrest, cmbCategoriePrest, cmbSpecialitePrest, cmbVillePrest, jScrollPane2, tfNomPrest});

        pnlModifierPrestLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, tfTelFixePrest, tfTelMobilPrest});

        pnlModifierPrestLayout.setVerticalGroup(
            pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelIdPrest))
                .addGap(10, 10, 10)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNomPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfimage)
                        .addComponent(tfImagePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModifierPrestLayout.createSequentialGroup()
                        .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TfEmailPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TfPwdPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aa)
                        .addComponent(tfTelMobilPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbVillePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ff)
                    .addComponent(tfTelFixePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbCategoriePrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbSpecialitePrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlModifierPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValiderModifPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnulModifPrest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModifierPrestLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnulModifPrest, btnValiderModifPrest});

        tfNomPrest.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlModifierPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlModifierPrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTelFixePrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelFixePrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelFixePrestActionPerformed

    private void cmbVillePrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVillePrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVillePrestActionPerformed

    private void chkEmailValidePrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmailValidePrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEmailValidePrestActionPerformed

    private void chkPremiumPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPremiumPrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPremiumPrestActionPerformed

    private void btnValiderModifPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderModifPrestActionPerformed
Pattern pattern2 = Pattern.compile("(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)*\\@(?:\\w|[\\-_])+(?:\\.(?:\\w|[\\-_])+)+" );  
    Pattern pattern = Pattern.compile("^\\d+$");
    Matcher matcher3 = pattern2.matcher(TfEmailPrest.getText());
      Matcher matcher = pattern.matcher(tfTelFixePrest.getText());
         Matcher matcher2 = pattern.matcher(tfTelMobilPrest.getText());
       if(tfNomPrest.getText().equals("")|| taDescPrest.getText().equals("")|| TfEmailPrest.getText().equals("") || TfPwdPrest.getText().equals("") || taAdrPrest.getText().equals("") || cmbVillePrest.getSelectedItem().equals("--Choisir ville--")|| cmbSpecialitePrest.getSelectedItem().equals("--Choisir spécialité--")|| cmbCategoriePrest.getSelectedItem().equals("--Choisir catégorie--")||!matcher.matches()||!matcher.matches()){
           String ch="";
           if(tfNomPrest.getText().equals(""))
               ch+="Veuillez saisir le Nom du prestataire \n";
           
            if(taDescPrest.getText().equals(""))
               ch+="Veuillez preciser la description du prestataire  \n";
            if(taAdrPrest.getText().equals(""))
               ch+="Veuillez donner l'adresse du prestataire  \n";
            if(cmbVillePrest.getSelectedItem().toString().equals(""))
               ch+="Veuillez donner la ville du prestataire  \n";
            if(tfTelMobilPrest.getText().equals(""))
               ch+="Veuillez donner le numero de telephone mobile  du prestataire  \n";
             else if(!matcher2.matches())
                  ch+="Veuiller bien remplir le champ du numero de telephone mobile  du prestataire  \n";
             if(tfTelFixePrest.getText().equals(""))
               ch+="Veuillez donner le numero de telephone fixe du prestataire  \n";
             else if(!matcher.matches())
                  ch+="Veuiller bien remplir le champ du numero de telephone fixe du prestataire  \n";
              
              if(tfimage.getText().equals(""))
               ch+="Veuillez donner le chemin de l'image du prestataire  \n";
              if(TfEmailPrest.getText().equals(""))
               ch+="Veuillez donner l'adresse email du prestataire  \n";
              else if(!matcher3.matches())
                  ch+="Veuiller bien donner une adresse mail correcte du prestataire  \n";
              if(tfTelMobilPrest.getText().equals(""))
               ch+="Veuillez donner le numero de telephone mobile du prestataire  \n";
             if(cmbCategoriePrest.getSelectedItem().toString().equals(""))
               ch+="Veuillez donner la catégorie  du prestataire  \n";
              if(cmbSpecialitePrest.getSelectedItem().toString().equals(""))
               ch+="Veuillez donner la specialité  du prestataire  \n";
            int dialogButton = JOptionPane.OK_CANCEL_OPTION;
                JOptionPane.showConfirmDialog (null,ch,"Warning",dialogButton);
            
        }else{
            
            
           prest.setIdPrest(Integer.parseInt(labelIdPrest.getText()));
           
            prest.setNomPrest(tfNomPrest.getText());
           
             prest.setDescPrest(taDescPrest.getText());
             
             
           prest.setAdrPrest(taAdrPrest.getText());
           prest.setVillePrest(cmbVillePrest.getSelectedItem().toString());
           prest.setImgPrest(tfimage.getText());
           prest.setEmailPrest(TfEmailPrest.getText());
           
           prest.setPwdPrest(TfPwdPrest.getText());
           prest.setCategorie(cmbCategoriePrest.getSelectedItem().toString());
           
           prest.setCompteValide(chkCmptValidePrest.isSelected());
                     prest.setMailValide(chkEmailValidePrest.isSelected());
               
           prest.setDatePayement(tfDatePayementPrest.toString());
           prest.setPremium(chkPremiumPrest.isSelected());
           
                  prest.setSpecialite(cmbSpecialitePrest.getSelectedItem().toString());
                  
                  
           prest.setTelMobilePrest(tfTelMobilPrest.getText());
           prest.setTelFixePrest(tfTelMobilPrest.getText());
         presDAO.updatePrestataire(prest);
       
             this.setVisible(false);
             ListePrestataire lp=new ListePrestataire();
             lp.setVisible(true);
         }    }//GEN-LAST:event_btnValiderModifPrestActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
         
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAnulModifPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnulModifPrestActionPerformed

          this.dispose();
    }//GEN-LAST:event_btnAnulModifPrestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String chemin="";
        
       JFileChooser fc = new JFileChooser();
       
                int retval = fc.showOpenDialog(null);
                
                if (retval == JFileChooser.APPROVE_OPTION) {
                    
                    chemin = fc.getSelectedFile().getAbsolutePath();
                    
                    chemin = chemin.replace("\\", "/");    }                                            
    
                   tfImagePrest.setText(chemin);    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfDatePayementPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatePayementPrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatePayementPrestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modif_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modif_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modif_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modif_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
    }
    catch(Exception e)
    {
        //TODO exception
    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modif_Prest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfEmailPrest;
    private javax.swing.JPasswordField TfPwdPrest;
    private javax.swing.JLabel aa;
    private javax.swing.JButton btnAnulModifPrest;
    private javax.swing.JButton btnValiderModifPrest;
    private javax.swing.JCheckBox chkCmptValidePrest;
    private javax.swing.JCheckBox chkEmailValidePrest;
    private javax.swing.JCheckBox chkPremiumPrest;
    private javax.swing.JComboBox cmbCategoriePrest;
    private javax.swing.JComboBox cmbSpecialitePrest;
    private javax.swing.JComboBox cmbVillePrest;
    private javax.swing.JLabel ff;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelIdPrest;
    private javax.swing.JPanel pnlModifierPrest;
    private javax.swing.JTextArea taAdrPrest;
    private javax.swing.JTextArea taDescPrest;
    private javax.swing.JFormattedTextField tfDatePayementPrest;
    private javax.swing.JTextField tfImagePrest;
    private javax.swing.JTextField tfNomPrest;
    private javax.swing.JTextField tfTelFixePrest;
    private javax.swing.JTextField tfTelMobilPrest;
    private javax.swing.JLabel tfimage;
    // End of variables declaration//GEN-END:variables
}