/*
 * Copyright (C) 2014 Karim
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package tn.mariages.gui;




import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import tn.mariages.dao.AdminDAO;
import tn.mariages.entities.Admin;
import tn.mariages.dao.ClientDAO;
import tn.mariages.entities.Client;
import tn.mariages.dao.PrestataireDAO;
import tn.mariages.entities.Prestataire;
import tn.mariages.util.*;
/**
 *
 * @author Karim
 */
public class MotDePasseOublie extends javax.swing.JFrame {

    /**
     * Creates new form MotDePasseOublié
     */
    public MotDePasseOublie() {
        initComponents();

        try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
            UIManager.put("RootPane.setupButtonVisible", false);

    }
    catch(Exception e)
    {
        //TODO exception
    }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEnvoyer = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfEmail.setToolTipText("");

        jLabel1.setText("Email :");

        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        labelMessage.setForeground(new java.awt.Color(253, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(labelMessage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnEnvoyer)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(labelMessage)
                .addGap(18, 18, 18)
                .addComponent(btnEnvoyer))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

 
public String generate(int length)
{
	    String chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"; 
	    String pass = "";
	    for(int x=0;x<length;x++)
	    {
	       int i = (int)Math.floor(Math.random() * 62); 
	       pass += chars.charAt(i);
	    }
	   
	    return pass;
}
    
    
    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
       
        
        AdminDAO adminDAO=new AdminDAO();
        ClientDAO clientDAO=new ClientDAO();
        PrestataireDAO prestataireDAO=new PrestataireDAO();
        Admin admin=new Admin();
       Client client=new Client();
       Prestataire prestataire=new Prestataire();
        SimpleMail s1=new SimpleMail();
   String mdp=generate(10);
   
     MessageDigest md = null;
    try {
        md = MessageDigest.getInstance("SHA-1");
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }
        ByteArrayInputStream fis = new ByteArrayInputStream(mdp.getBytes());

        byte[] dataBytes = new byte[1024];

        int nread = 0; 
    try {
        while ((nread = fis.read(dataBytes)) != -1) {
            md.update(dataBytes, 0, nread);
        }
    } catch (IOException ex) {
        Logger.getLogger(InscriptionClient.class.getName()).log(Level.SEVERE, null, ex);
    }

        byte[] mdbytes = md.digest();

        //convert the byte to hex format method 1
        StringBuffer pwd1 = new StringBuffer();
        for (int i = 0; i < mdbytes.length; i++) {
          pwd1.append(Integer.toString((mdbytes[i] & 0xff) + 0x100, 16).substring(1));
        }
   
   
   
   if(adminDAO.findAdminByEmailBoolean(tfEmail.getText())){
       admin=adminDAO.findAdminByEmail(tfEmail.getText());
   s1.SendMail(tfEmail.getText(), "Mot de passe oublié", "Votre nouveau mot de passe : "+mdp);
   admin.setPwdAdmin(pwd1.toString());
   adminDAO.updateAdmin(admin);
   }
   
   else if(clientDAO.findClientByEmailBoolean(tfEmail.getText())){
   client=clientDAO.findClientByEmail(tfEmail.getText());
   s1.SendMail(tfEmail.getText(), "Mot de passe oublié", "Votre nouveau mot de passe : "+mdp);
   client.setPwdClient(pwd1.toString());
   clientDAO.updateClient(client);
   }
   
   else if(prestataireDAO.findPrestByEmailBoolean(tfEmail.getText())){
   prestataire=prestataireDAO.findPrestByEmail(tfEmail.getText());
   s1.SendMail(tfEmail.getText(), "Mot de passe oublié", "Votre nouveau mot de passe : "+mdp);
   prestataire.setPwdPrest(pwd1.toString());
   prestataireDAO.updatePrestataire(prestataire);
   
   }
   
   else {
    int dialogButton = JOptionPane.OK_OPTION;
          JOptionPane.showConfirmDialog (null, "L'email que vous avez saisi n'existe pas","ERROR",dialogButton);
   
   }
       
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotDePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try
    {
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
            UIManager.put("RootPane.setupButtonVisible", false);

    }
    catch(Exception e)
    {
        //TODO exception
    }

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotDePasseOublie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}
